/**
 * MECE list of medical specialties used across the platform.
 * Alphabetically sorted. Update this single file to change everywhere.
 */
export const SPECIALTIES = [
  "Anaesthesia & Critical Care",
  "Cardiology",
  "Cardiothoracic Surgery",
  "Clinical Pharmacology",
  "Dentistry & Oral Surgery",
  "Dermatology",
  "Emergency Medicine",
  "Endocrinology & Diabetes",
  "ENT (Otorhinolaryngology)",
  "Family Medicine / General Practice",
  "Finance",
  "Gastroenterology",
  "General Surgery",
  "Geriatric Medicine",
  "Haematology",
  "Infectious Diseases",
  "Internal Medicine",
  "Management Consulting",
  "Maxillofacial Surgery",
  "Neonatology",
  "Nephrology",
  "Neurology",
  "Neurosurgery",
  "Obstetrics & Gynaecology",
  "Occupational Medicine",
  "Oncology",
  "Ophthalmology",
  "Oral & Maxillofacial Surgery",
  "Orthopaedic Surgery",
  "Paediatric Surgery",
  "Paediatrics",
  "Palliative Medicine",
  "Pathology",
  "Plastic & Reconstructive Surgery",
  "Psychiatry",
  "Public Health",
  "Pulmonology / Respiratory Medicine",
  "Radiology",
  "Rehabilitation Medicine",
  "Rheumatology",
  "Sports Medicine",
  "Trauma Surgery",
  "Urology",
  "Vascular Surgery",
  "Other",
] as const;

export type Specialty = (typeof SPECIALTIES)[number];
