import { PrismaClient } from '@prisma/client';

const investigations = [
  // ═══════════════════════════════════════════════════════════════
  // HAEMATOLOGY (35 tests)
  // ═══════════════════════════════════════════════════════════════
  {
    loincCode: "58410-2",
    name: "Full Blood Count",
    commonName: "FBC",
    category: "HAEMATOLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 100,
  },
  {
    loincCode: "30341-2",
    name: "Erythrocyte Sedimentation Rate",
    commonName: "ESR",
    category: "HAEMATOLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 90,
  },
  {
    loincCode: "24317-0",
    name: "Haemoglobin Concentration",
    commonName: null,
    category: "HAEMATOLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 95,
  },
  {
    loincCode: "33765-9",
    name: "White Blood Cell Count",
    commonName: "WBC",
    category: "HAEMATOLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 90,
  },
  {
    loincCode: "26515-7",
    name: "Platelet Count",
    commonName: null,
    category: "HAEMATOLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 88,
  },
  {
    loincCode: "24331-1",
    name: "Peripheral Blood Film",
    commonName: "Blood film",
    category: "HAEMATOLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 80,
  },
  {
    loincCode: "35474-6",
    name: "Sickle Cell Screen",
    commonName: "Sickling test",
    category: "HAEMATOLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 90,
  },
  {
    loincCode: "13514-5",
    name: "Haemoglobin Electrophoresis",
    commonName: "Hb electrophoresis",
    category: "HAEMATOLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 90,
  },
  {
    loincCode: "4548-4",
    name: "Glycated Haemoglobin",
    commonName: "HbA1c",
    category: "HAEMATOLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 80,
  },
  {
    loincCode: "17849-1",
    name: "Reticulocyte Count",
    commonName: "Retics",
    category: "HAEMATOLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 70,
  },
  {
    loincCode: "5902-2",
    name: "Prothrombin Time / INR",
    commonName: "PT/INR",
    category: "HAEMATOLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 80,
  },
  {
    loincCode: "3173-2",
    name: "Activated Partial Thromboplastin Time",
    commonName: "aPTT",
    category: "HAEMATOLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 75,
  },
  {
    loincCode: "11067-6",
    name: "Bleeding Time",
    commonName: null,
    category: "HAEMATOLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 70,
  },
  {
    loincCode: "3184-9",
    name: "Clotting Time",
    commonName: null,
    category: "HAEMATOLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 72,
  },
  {
    loincCode: "48065-7",
    name: "D-Dimer",
    commonName: "D-Dimer",
    category: "HAEMATOLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 70,
  },
  {
    loincCode: "882-1",
    name: "Blood Group and Type (ABO/Rh)",
    commonName: "Blood group",
    category: "HAEMATOLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 85,
  },
  {
    loincCode: "1250-0",
    name: "Cross-Match",
    commonName: "Group and cross-match",
    category: "HAEMATOLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 80,
  },
  {
    loincCode: "1006-6",
    name: "Direct Coombs Test",
    commonName: "DCT",
    category: "HAEMATOLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 60,
  },
  {
    loincCode: "1007-4",
    name: "Indirect Coombs Test",
    commonName: "ICT",
    category: "HAEMATOLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 60,
  },
  {
    loincCode: "32546-4",
    name: "Glucose-6-Phosphate Dehydrogenase Assay",
    commonName: "G6PD",
    category: "HAEMATOLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 80,
  },
  {
    loincCode: "26453-1",
    name: "Red Blood Cell Count",
    commonName: "RBC",
    category: "HAEMATOLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 85,
  },
  {
    loincCode: "28540-3",
    name: "Mean Corpuscular Volume",
    commonName: "MCV",
    category: "HAEMATOLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 80,
  },
  {
    loincCode: "28539-5",
    name: "Mean Corpuscular Haemoglobin",
    commonName: "MCH",
    category: "HAEMATOLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 78,
  },
  {
    loincCode: "28542-9",
    name: "Mean Corpuscular Haemoglobin Concentration",
    commonName: "MCHC",
    category: "HAEMATOLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 78,
  },
  {
    loincCode: "30384-2",
    name: "Red Cell Distribution Width",
    commonName: "RDW",
    category: "HAEMATOLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 70,
  },
  {
    loincCode: "26444-0",
    name: "Packed Cell Volume",
    commonName: "PCV",
    category: "HAEMATOLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 92,
  },
  {
    loincCode: "770-8",
    name: "Neutrophil Count",
    commonName: null,
    category: "HAEMATOLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 75,
  },
  {
    loincCode: "731-0",
    name: "Lymphocyte Count",
    commonName: null,
    category: "HAEMATOLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 75,
  },
  {
    loincCode: "742-7",
    name: "Monocyte Count",
    commonName: null,
    category: "HAEMATOLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 70,
  },
  {
    loincCode: "711-2",
    name: "Eosinophil Count",
    commonName: null,
    category: "HAEMATOLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 70,
  },
  {
    loincCode: "704-7",
    name: "Basophil Count",
    commonName: null,
    category: "HAEMATOLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 65,
  },
  {
    loincCode: "3255-7",
    name: "Fibrinogen Level",
    commonName: null,
    category: "HAEMATOLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 60,
  },
  {
    loincCode: "6690-2",
    name: "White Cell Differential Count",
    commonName: "WBC diff",
    category: "HAEMATOLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 85,
  },
  {
    loincCode: "34714-6",
    name: "Thrombin Time",
    commonName: "TT",
    category: "HAEMATOLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 55,
  },
  {
    loincCode: "75217-0",
    name: "Bone Marrow Aspirate and Biopsy",
    commonName: "BMA",
    category: "HAEMATOLOGY",
    sampleType: "TISSUE",
    fastingRequired: false,
    nigeriaWeighting: 50,
  },

  // ═══════════════════════════════════════════════════════════════
  // BIOCHEMISTRY (45 tests)
  // ═══════════════════════════════════════════════════════════════
  {
    loincCode: "24325-3",
    name: "Liver Function Tests",
    commonName: "LFT",
    category: "BIOCHEMISTRY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 90,
  },
  {
    loincCode: "1975-2",
    name: "Total Bilirubin",
    commonName: null,
    category: "BIOCHEMISTRY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 85,
  },
  {
    loincCode: "1968-7",
    name: "Direct Bilirubin",
    commonName: "Conjugated bilirubin",
    category: "BIOCHEMISTRY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 82,
  },
  {
    loincCode: "1920-8",
    name: "Aspartate Aminotransferase",
    commonName: "AST/SGOT",
    category: "BIOCHEMISTRY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 88,
  },
  {
    loincCode: "1742-6",
    name: "Alanine Aminotransferase",
    commonName: "ALT/SGPT",
    category: "BIOCHEMISTRY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 88,
  },
  {
    loincCode: "6768-6",
    name: "Alkaline Phosphatase",
    commonName: "ALP",
    category: "BIOCHEMISTRY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 85,
  },
  {
    loincCode: "2324-2",
    name: "Gamma-Glutamyl Transferase",
    commonName: "GGT",
    category: "BIOCHEMISTRY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 78,
  },
  {
    loincCode: "2885-2",
    name: "Total Protein",
    commonName: null,
    category: "BIOCHEMISTRY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 80,
  },
  {
    loincCode: "1751-7",
    name: "Serum Albumin",
    commonName: "Albumin",
    category: "BIOCHEMISTRY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 82,
  },
  {
    loincCode: "24362-6",
    name: "Renal Function Tests / Urea & Electrolytes",
    commonName: "U&E / RFT",
    category: "BIOCHEMISTRY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 90,
  },
  {
    loincCode: "3094-0",
    name: "Blood Urea Nitrogen",
    commonName: "Urea",
    category: "BIOCHEMISTRY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 88,
  },
  {
    loincCode: "2160-0",
    name: "Serum Creatinine",
    commonName: "Creatinine",
    category: "BIOCHEMISTRY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 88,
  },
  {
    loincCode: "2951-2",
    name: "Serum Sodium",
    commonName: "Na+",
    category: "BIOCHEMISTRY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 85,
  },
  {
    loincCode: "2823-3",
    name: "Serum Potassium",
    commonName: "K+",
    category: "BIOCHEMISTRY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 85,
  },
  {
    loincCode: "2075-0",
    name: "Serum Chloride",
    commonName: "Cl-",
    category: "BIOCHEMISTRY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 80,
  },
  {
    loincCode: "1963-8",
    name: "Serum Bicarbonate",
    commonName: "HCO3-",
    category: "BIOCHEMISTRY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 80,
  },
  {
    loincCode: "1558-6",
    name: "Fasting Blood Glucose",
    commonName: "FBG",
    category: "BIOCHEMISTRY",
    sampleType: "BLOOD",
    fastingRequired: true,
    nigeriaWeighting: 85,
  },
  {
    loincCode: "2345-7",
    name: "Random Blood Glucose",
    commonName: "RBG",
    category: "BIOCHEMISTRY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 85,
  },
  {
    loincCode: "20438-8",
    name: "2-Hour Post-Prandial Blood Glucose",
    commonName: "2hr PP glucose",
    category: "BIOCHEMISTRY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 78,
  },
  {
    loincCode: "77145-1",
    name: "Oral Glucose Tolerance Test",
    commonName: "OGTT",
    category: "BIOCHEMISTRY",
    sampleType: "BLOOD",
    fastingRequired: true,
    nigeriaWeighting: 72,
  },
  {
    loincCode: "24331-2",
    name: "Fasting Lipid Profile",
    commonName: "Lipid profile",
    category: "BIOCHEMISTRY",
    sampleType: "BLOOD",
    fastingRequired: true,
    nigeriaWeighting: 80,
  },
  {
    loincCode: "2093-3",
    name: "Total Cholesterol",
    commonName: null,
    category: "BIOCHEMISTRY",
    sampleType: "BLOOD",
    fastingRequired: true,
    nigeriaWeighting: 78,
  },
  {
    loincCode: "13457-7",
    name: "Low-Density Lipoprotein Cholesterol",
    commonName: "LDL",
    category: "BIOCHEMISTRY",
    sampleType: "BLOOD",
    fastingRequired: true,
    nigeriaWeighting: 78,
  },
  {
    loincCode: "2085-9",
    name: "High-Density Lipoprotein Cholesterol",
    commonName: "HDL",
    category: "BIOCHEMISTRY",
    sampleType: "BLOOD",
    fastingRequired: true,
    nigeriaWeighting: 78,
  },
  {
    loincCode: "2571-8",
    name: "Triglycerides",
    commonName: null,
    category: "BIOCHEMISTRY",
    sampleType: "BLOOD",
    fastingRequired: true,
    nigeriaWeighting: 76,
  },
  {
    loincCode: "3084-1",
    name: "Serum Uric Acid",
    commonName: "Uric acid",
    category: "BIOCHEMISTRY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 72,
  },
  {
    loincCode: "17861-6",
    name: "Serum Calcium",
    commonName: "Ca2+",
    category: "BIOCHEMISTRY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 70,
  },
  {
    loincCode: "2777-1",
    name: "Serum Phosphate",
    commonName: "PO4",
    category: "BIOCHEMISTRY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 65,
  },
  {
    loincCode: "19123-9",
    name: "Serum Magnesium",
    commonName: "Mg2+",
    category: "BIOCHEMISTRY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 62,
  },
  {
    loincCode: "2498-4",
    name: "Serum Iron",
    commonName: null,
    category: "BIOCHEMISTRY",
    sampleType: "BLOOD",
    fastingRequired: true,
    nigeriaWeighting: 68,
  },
  {
    loincCode: "2500-7",
    name: "Total Iron Binding Capacity",
    commonName: "TIBC",
    category: "BIOCHEMISTRY",
    sampleType: "BLOOD",
    fastingRequired: true,
    nigeriaWeighting: 65,
  },
  {
    loincCode: "2276-4",
    name: "Serum Ferritin",
    commonName: "Ferritin",
    category: "BIOCHEMISTRY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 70,
  },
  {
    loincCode: "1798-8",
    name: "Serum Amylase",
    commonName: "Amylase",
    category: "BIOCHEMISTRY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 65,
  },
  {
    loincCode: "3040-3",
    name: "Serum Lipase",
    commonName: "Lipase",
    category: "BIOCHEMISTRY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 62,
  },
  {
    loincCode: "10839-9",
    name: "Troponin I",
    commonName: null,
    category: "BIOCHEMISTRY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 75,
  },
  {
    loincCode: "6598-7",
    name: "Troponin T",
    commonName: null,
    category: "BIOCHEMISTRY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 72,
  },
  {
    loincCode: "49563-0",
    name: "Creatine Kinase-MB",
    commonName: "CK-MB",
    category: "BIOCHEMISTRY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 70,
  },
  {
    loincCode: "2532-0",
    name: "Lactate Dehydrogenase",
    commonName: "LDH",
    category: "BIOCHEMISTRY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 68,
  },
  {
    loincCode: "30934-4",
    name: "B-Type Natriuretic Peptide",
    commonName: "BNP",
    category: "BIOCHEMISTRY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 60,
  },
  {
    loincCode: "33762-6",
    name: "NT-proBNP",
    commonName: null,
    category: "BIOCHEMISTRY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 60,
  },
  {
    loincCode: "1988-5",
    name: "C-Reactive Protein",
    commonName: "CRP",
    category: "BIOCHEMISTRY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 80,
  },
  {
    loincCode: "30522-7",
    name: "High-Sensitivity C-Reactive Protein",
    commonName: "hs-CRP",
    category: "BIOCHEMISTRY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 65,
  },
  {
    loincCode: "75241-0",
    name: "Procalcitonin",
    commonName: "PCT",
    category: "BIOCHEMISTRY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 60,
  },
  {
    loincCode: "33037-3",
    name: "Estimated Glomerular Filtration Rate",
    commonName: "eGFR",
    category: "BIOCHEMISTRY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 75,
  },
  {
    loincCode: "2157-6",
    name: "Creatine Kinase Total",
    commonName: "CK total",
    category: "BIOCHEMISTRY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 60,
  },

  // ═══════════════════════════════════════════════════════════════
  // MICROBIOLOGY (32 tests)
  // ═══════════════════════════════════════════════════════════════
  {
    loincCode: "600-7",
    name: "Blood Culture and Sensitivity",
    commonName: "Blood C/S",
    category: "MICROBIOLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 85,
  },
  {
    loincCode: "630-4",
    name: "Urine Microscopy, Culture and Sensitivity",
    commonName: "Urine MCS",
    category: "MICROBIOLOGY",
    sampleType: "URINE",
    fastingRequired: false,
    nigeriaWeighting: 90,
  },
  {
    loincCode: "625-4",
    name: "Stool Microscopy, Culture and Sensitivity",
    commonName: "Stool MCS",
    category: "MICROBIOLOGY",
    sampleType: "STOOL",
    fastingRequired: false,
    nigeriaWeighting: 80,
  },
  {
    loincCode: "6463-4",
    name: "Wound Swab Microscopy, Culture and Sensitivity",
    commonName: "Wound swab MCS",
    category: "MICROBIOLOGY",
    sampleType: "SWAB",
    fastingRequired: false,
    nigeriaWeighting: 78,
  },
  {
    loincCode: "6462-6",
    name: "High Vaginal Swab Microscopy, Culture and Sensitivity",
    commonName: "HVS MCS",
    category: "MICROBIOLOGY",
    sampleType: "SWAB",
    fastingRequired: false,
    nigeriaWeighting: 75,
  },
  {
    loincCode: "691-6",
    name: "Urethral Swab Microscopy, Culture and Sensitivity",
    commonName: "Urethral swab MCS",
    category: "MICROBIOLOGY",
    sampleType: "SWAB",
    fastingRequired: false,
    nigeriaWeighting: 70,
  },
  {
    loincCode: "624-7",
    name: "Sputum Microscopy, Culture and Sensitivity",
    commonName: "Sputum MCS",
    category: "MICROBIOLOGY",
    sampleType: "OTHER",
    fastingRequired: false,
    nigeriaWeighting: 78,
  },
  {
    loincCode: "29575-8",
    name: "Cerebrospinal Fluid Analysis (MCS + Biochemistry)",
    commonName: "CSF analysis",
    category: "MICROBIOLOGY",
    sampleType: "OTHER",
    fastingRequired: false,
    nigeriaWeighting: 70,
  },
  {
    loincCode: "32700-7",
    name: "Malaria Parasite (Thick and Thin Film)",
    commonName: "MP",
    category: "MICROBIOLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 100,
  },
  {
    loincCode: "70568-1",
    name: "Malaria Rapid Diagnostic Test",
    commonName: "mRDT",
    category: "MICROBIOLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 95,
  },
  {
    loincCode: "94500-6",
    name: "TB GeneXpert (Xpert MTB/RIF)",
    commonName: "GeneXpert",
    category: "MICROBIOLOGY",
    sampleType: "OTHER",
    fastingRequired: false,
    nigeriaWeighting: 80,
  },
  {
    loincCode: "11545-1",
    name: "Acid-Fast Bacilli Smear (Ziehl-Neelsen Stain)",
    commonName: "AFB / ZN stain",
    category: "MICROBIOLOGY",
    sampleType: "OTHER",
    fastingRequired: false,
    nigeriaWeighting: 75,
  },
  {
    loincCode: "543-9",
    name: "Sputum AFB Culture",
    commonName: "TB culture",
    category: "MICROBIOLOGY",
    sampleType: "OTHER",
    fastingRequired: false,
    nigeriaWeighting: 70,
  },
  {
    loincCode: "55277-8",
    name: "Mantoux Test (Tuberculin Skin Test)",
    commonName: "Mantoux",
    category: "MICROBIOLOGY",
    sampleType: "OTHER",
    fastingRequired: false,
    nigeriaWeighting: 72,
  },
  {
    loincCode: "626-2",
    name: "Stool Ova and Parasites",
    commonName: "Stool O&P",
    category: "MICROBIOLOGY",
    sampleType: "STOOL",
    fastingRequired: false,
    nigeriaWeighting: 82,
  },
  {
    loincCode: "6584-7",
    name: "Stool Occult Blood",
    commonName: "Stool OB",
    category: "MICROBIOLOGY",
    sampleType: "STOOL",
    fastingRequired: false,
    nigeriaWeighting: 70,
  },
  {
    loincCode: "10351-5",
    name: "Ear Swab Microscopy, Culture and Sensitivity",
    commonName: "Ear swab MCS",
    category: "MICROBIOLOGY",
    sampleType: "SWAB",
    fastingRequired: false,
    nigeriaWeighting: 68,
  },
  {
    loincCode: "6461-8",
    name: "Throat Swab Microscopy, Culture and Sensitivity",
    commonName: "Throat swab MCS",
    category: "MICROBIOLOGY",
    sampleType: "SWAB",
    fastingRequired: false,
    nigeriaWeighting: 68,
  },
  {
    loincCode: "6460-0",
    name: "Eye Swab Microscopy, Culture and Sensitivity",
    commonName: "Eye swab MCS",
    category: "MICROBIOLOGY",
    sampleType: "SWAB",
    fastingRequired: false,
    nigeriaWeighting: 65,
  },
  {
    loincCode: "580-1",
    name: "Nasal Swab Culture",
    commonName: "Nasal swab MCS",
    category: "MICROBIOLOGY",
    sampleType: "SWAB",
    fastingRequired: false,
    nigeriaWeighting: 60,
  },
  {
    loincCode: "90441-7",
    name: "Skin Snip Microscopy (Onchocerciasis)",
    commonName: "Skin snip",
    category: "MICROBIOLOGY",
    sampleType: "TISSUE",
    fastingRequired: false,
    nigeriaWeighting: 60,
  },
  {
    loincCode: "6396-6",
    name: "Seminal Fluid Analysis",
    commonName: "SFA / Semen analysis",
    category: "MICROBIOLOGY",
    sampleType: "OTHER",
    fastingRequired: false,
    nigeriaWeighting: 65,
  },
  {
    loincCode: "87426-4",
    name: "Gram Stain",
    commonName: null,
    category: "MICROBIOLOGY",
    sampleType: "SWAB",
    fastingRequired: false,
    nigeriaWeighting: 72,
  },
  {
    loincCode: "53926-2",
    name: "Chlamydia trachomatis PCR",
    commonName: "Chlamydia test",
    category: "MICROBIOLOGY",
    sampleType: "SWAB",
    fastingRequired: false,
    nigeriaWeighting: 60,
  },
  {
    loincCode: "21415-5",
    name: "Neisseria gonorrhoeae PCR",
    commonName: "Gonorrhoea test",
    category: "MICROBIOLOGY",
    sampleType: "SWAB",
    fastingRequired: false,
    nigeriaWeighting: 62,
  },
  {
    loincCode: "6349-5",
    name: "KOH Preparation (Fungal)",
    commonName: "KOH mount",
    category: "MICROBIOLOGY",
    sampleType: "SWAB",
    fastingRequired: false,
    nigeriaWeighting: 65,
  },
  {
    loincCode: "580-2",
    name: "Fungal Culture and Sensitivity",
    commonName: "Fungal C/S",
    category: "MICROBIOLOGY",
    sampleType: "SWAB",
    fastingRequired: false,
    nigeriaWeighting: 58,
  },
  {
    loincCode: "5769-5",
    name: "Urinalysis with Wet Mount (Trichomonas)",
    commonName: "Wet prep",
    category: "MICROBIOLOGY",
    sampleType: "SWAB",
    fastingRequired: false,
    nigeriaWeighting: 65,
  },
  {
    loincCode: "32774-2",
    name: "Thick Blood Film for Filariasis",
    commonName: "Microfilaria",
    category: "MICROBIOLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 55,
  },
  {
    loincCode: "10724-3",
    name: "Stool Reducing Substances",
    commonName: null,
    category: "MICROBIOLOGY",
    sampleType: "STOOL",
    fastingRequired: false,
    nigeriaWeighting: 50,
  },
  {
    loincCode: "11546-9",
    name: "Blood Film for Trypanosomes",
    commonName: null,
    category: "MICROBIOLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 45,
  },
  {
    loincCode: "72357-7",
    name: "Aspirate for Microscopy, Culture and Sensitivity",
    commonName: "Aspirate MCS",
    category: "MICROBIOLOGY",
    sampleType: "OTHER",
    fastingRequired: false,
    nigeriaWeighting: 60,
  },

  // ═══════════════════════════════════════════════════════════════
  // SEROLOGY (25 tests)
  // ═══════════════════════════════════════════════════════════════
  {
    loincCode: "68961-2",
    name: "HIV 1&2 Antigen/Antibody Combo",
    commonName: "HIV screening",
    category: "SEROLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 90,
  },
  {
    loincCode: "5196-1",
    name: "Hepatitis B Surface Antigen",
    commonName: "HBsAg",
    category: "SEROLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 90,
  },
  {
    loincCode: "22322-2",
    name: "Hepatitis B Surface Antibody",
    commonName: "HBsAb",
    category: "SEROLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 75,
  },
  {
    loincCode: "16933-4",
    name: "Hepatitis B Core Antibody",
    commonName: "HBcAb",
    category: "SEROLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 72,
  },
  {
    loincCode: "13954-3",
    name: "Hepatitis B e Antigen",
    commonName: "HBeAg",
    category: "SEROLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 70,
  },
  {
    loincCode: "13953-5",
    name: "Hepatitis B e Antibody",
    commonName: "HBeAb",
    category: "SEROLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 68,
  },
  {
    loincCode: "16128-1",
    name: "Hepatitis C Antibody",
    commonName: "Anti-HCV",
    category: "SEROLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 85,
  },
  {
    loincCode: "11259-9",
    name: "Hepatitis C Virus RNA (Viral Load)",
    commonName: "HCV viral load",
    category: "SEROLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 70,
  },
  {
    loincCode: "25836-8",
    name: "HIV-1 RNA (Viral Load)",
    commonName: "HIV viral load",
    category: "SEROLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 80,
  },
  {
    loincCode: "24467-3",
    name: "CD4 Count",
    commonName: "CD4",
    category: "SEROLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 80,
  },
  {
    loincCode: "5288-6",
    name: "Widal Test (Salmonella Agglutination)",
    commonName: "Widal",
    category: "SEROLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 85,
  },
  {
    loincCode: "20507-0",
    name: "VDRL / RPR (Syphilis Screen)",
    commonName: "VDRL",
    category: "SEROLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 78,
  },
  {
    loincCode: "11572-5",
    name: "Rheumatoid Factor",
    commonName: "RF",
    category: "SEROLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 62,
  },
  {
    loincCode: "8061-4",
    name: "Antinuclear Antibody",
    commonName: "ANA",
    category: "SEROLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 55,
  },
  {
    loincCode: "21419-7",
    name: "Anti-Neutrophil Cytoplasmic Antibody",
    commonName: "ANCA",
    category: "SEROLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 50,
  },
  {
    loincCode: "1742-8",
    name: "Anti-Streptolysin O Titre",
    commonName: "ASO titre",
    category: "SEROLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 72,
  },
  {
    loincCode: "22587-0",
    name: "Brucella Serology",
    commonName: null,
    category: "SEROLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 55,
  },
  {
    loincCode: "6526-8",
    name: "Helicobacter pylori Antibody",
    commonName: "H. pylori Ab",
    category: "SEROLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 70,
  },
  {
    loincCode: "60294-5",
    name: "Helicobacter pylori Stool Antigen",
    commonName: "H. pylori Ag",
    category: "SEROLOGY",
    sampleType: "STOOL",
    fastingRequired: false,
    nigeriaWeighting: 68,
  },
  {
    loincCode: "19080-1",
    name: "Serum Beta-hCG (Pregnancy Test)",
    commonName: "Beta-hCG",
    category: "SEROLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 80,
  },
  {
    loincCode: "73826-0",
    name: "Hepatitis B Virus DNA (Viral Load)",
    commonName: "HBV DNA",
    category: "SEROLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 72,
  },
  {
    loincCode: "47241-5",
    name: "Hepatitis A IgM Antibody",
    commonName: "HAV IgM",
    category: "SEROLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 58,
  },
  {
    loincCode: "29539-4",
    name: "Toxoplasma IgG/IgM",
    commonName: "TORCH - Toxo",
    category: "SEROLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 60,
  },
  {
    loincCode: "40667-8",
    name: "Rubella IgG/IgM",
    commonName: "TORCH - Rubella",
    category: "SEROLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 58,
  },
  {
    loincCode: "22244-8",
    name: "CMV IgG/IgM",
    commonName: "TORCH - CMV",
    category: "SEROLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 55,
  },

  // ═══════════════════════════════════════════════════════════════
  // ENDOCRINOLOGY (23 tests)
  // ═══════════════════════════════════════════════════════════════
  {
    loincCode: "11580-8",
    name: "Thyroid Stimulating Hormone",
    commonName: "TSH",
    category: "ENDOCRINOLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 80,
  },
  {
    loincCode: "3051-0",
    name: "Free Triiodothyronine",
    commonName: "Free T3",
    category: "ENDOCRINOLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 75,
  },
  {
    loincCode: "3024-7",
    name: "Free Thyroxine",
    commonName: "Free T4",
    category: "ENDOCRINOLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 78,
  },
  {
    loincCode: "2857-1",
    name: "Prostate Specific Antigen",
    commonName: "PSA",
    category: "ENDOCRINOLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 75,
  },
  {
    loincCode: "10501-5",
    name: "Luteinizing Hormone",
    commonName: "LH",
    category: "ENDOCRINOLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 60,
  },
  {
    loincCode: "15067-2",
    name: "Follicle Stimulating Hormone",
    commonName: "FSH",
    category: "ENDOCRINOLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 60,
  },
  {
    loincCode: "2243-4",
    name: "Oestradiol (Estradiol)",
    commonName: "E2",
    category: "ENDOCRINOLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 58,
  },
  {
    loincCode: "2839-9",
    name: "Progesterone",
    commonName: null,
    category: "ENDOCRINOLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 58,
  },
  {
    loincCode: "2986-8",
    name: "Testosterone (Total)",
    commonName: null,
    category: "ENDOCRINOLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 62,
  },
  {
    loincCode: "2991-8",
    name: "Free Testosterone",
    commonName: null,
    category: "ENDOCRINOLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 55,
  },
  {
    loincCode: "15081-3",
    name: "Prolactin",
    commonName: null,
    category: "ENDOCRINOLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 60,
  },
  {
    loincCode: "2143-6",
    name: "Cortisol (Morning)",
    commonName: "AM cortisol",
    category: "ENDOCRINOLOGY",
    sampleType: "BLOOD",
    fastingRequired: true,
    nigeriaWeighting: 58,
  },
  {
    loincCode: "2144-4",
    name: "Cortisol (Evening)",
    commonName: "PM cortisol",
    category: "ENDOCRINOLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 55,
  },
  {
    loincCode: "2141-0",
    name: "Adrenocorticotropic Hormone",
    commonName: "ACTH",
    category: "ENDOCRINOLOGY",
    sampleType: "BLOOD",
    fastingRequired: true,
    nigeriaWeighting: 50,
  },
  {
    loincCode: "2963-7",
    name: "Growth Hormone",
    commonName: "GH",
    category: "ENDOCRINOLOGY",
    sampleType: "BLOOD",
    fastingRequired: true,
    nigeriaWeighting: 50,
  },
  {
    loincCode: "2484-4",
    name: "Fasting Insulin",
    commonName: null,
    category: "ENDOCRINOLOGY",
    sampleType: "BLOOD",
    fastingRequired: true,
    nigeriaWeighting: 58,
  },
  {
    loincCode: "1986-9",
    name: "C-Peptide",
    commonName: null,
    category: "ENDOCRINOLOGY",
    sampleType: "BLOOD",
    fastingRequired: true,
    nigeriaWeighting: 52,
  },
  {
    loincCode: "1989-3",
    name: "25-Hydroxyvitamin D",
    commonName: "Vitamin D",
    category: "ENDOCRINOLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 60,
  },
  {
    loincCode: "2731-8",
    name: "Parathyroid Hormone",
    commonName: "PTH",
    category: "ENDOCRINOLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 55,
  },
  {
    loincCode: "10334-1",
    name: "Cancer Antigen 125",
    commonName: "CA-125",
    category: "ENDOCRINOLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 58,
  },
  {
    loincCode: "2039-6",
    name: "Carcinoembryonic Antigen",
    commonName: "CEA",
    category: "ENDOCRINOLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 55,
  },
  {
    loincCode: "1834-1",
    name: "Alpha-Fetoprotein",
    commonName: "AFP",
    category: "ENDOCRINOLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 60,
  },
  {
    loincCode: "83080-3",
    name: "Thyroid Peroxidase Antibody",
    commonName: "Anti-TPO",
    category: "ENDOCRINOLOGY",
    sampleType: "BLOOD",
    fastingRequired: false,
    nigeriaWeighting: 55,
  },

  // ═══════════════════════════════════════════════════════════════
  // URINALYSIS (8 tests)
  // ═══════════════════════════════════════════════════════════════
  {
    loincCode: "24356-8",
    name: "Urinalysis (Dipstick and Microscopy)",
    commonName: "Urinalysis",
    category: "URINALYSIS",
    sampleType: "URINE",
    fastingRequired: false,
    nigeriaWeighting: 90,
  },
  {
    loincCode: "2889-4",
    name: "24-Hour Urine Protein",
    commonName: "24hr urine protein",
    category: "URINALYSIS",
    sampleType: "URINE",
    fastingRequired: false,
    nigeriaWeighting: 72,
  },
  {
    loincCode: "9318-7",
    name: "Urine Albumin-Creatinine Ratio",
    commonName: "uACR",
    category: "URINALYSIS",
    sampleType: "URINE",
    fastingRequired: false,
    nigeriaWeighting: 75,
  },
  {
    loincCode: "2162-6",
    name: "Urine Creatinine",
    commonName: null,
    category: "URINALYSIS",
    sampleType: "URINE",
    fastingRequired: false,
    nigeriaWeighting: 68,
  },
  {
    loincCode: "2956-1",
    name: "Urine Sodium",
    commonName: null,
    category: "URINALYSIS",
    sampleType: "URINE",
    fastingRequired: false,
    nigeriaWeighting: 60,
  },
  {
    loincCode: "2828-2",
    name: "Urine Potassium",
    commonName: null,
    category: "URINALYSIS",
    sampleType: "URINE",
    fastingRequired: false,
    nigeriaWeighting: 58,
  },
  {
    loincCode: "2106-3",
    name: "Urine Pregnancy Test",
    commonName: "UPT",
    category: "URINALYSIS",
    sampleType: "URINE",
    fastingRequired: false,
    nigeriaWeighting: 85,
  },
  {
    loincCode: "5811-5",
    name: "Urine Specific Gravity",
    commonName: null,
    category: "URINALYSIS",
    sampleType: "URINE",
    fastingRequired: false,
    nigeriaWeighting: 70,
  },

  // ═══════════════════════════════════════════════════════════════
  // IMAGING (35 tests)
  // ═══════════════════════════════════════════════════════════════
  {
    loincCode: "IMG-CXR-001",
    name: "Chest X-Ray (Posteroanterior)",
    commonName: "CXR PA",
    category: "IMAGING",
    sampleType: "OTHER",
    fastingRequired: false,
    nigeriaWeighting: 85,
  },
  {
    loincCode: "IMG-CXR-002",
    name: "Chest X-Ray (Lateral)",
    commonName: "CXR lateral",
    category: "IMAGING",
    sampleType: "OTHER",
    fastingRequired: false,
    nigeriaWeighting: 70,
  },
  {
    loincCode: "IMG-AXR-001",
    name: "Abdominal X-Ray (Plain)",
    commonName: "Plain AXR",
    category: "IMAGING",
    sampleType: "OTHER",
    fastingRequired: false,
    nigeriaWeighting: 75,
  },
  {
    loincCode: "IMG-USS-001",
    name: "Abdominal Ultrasound Scan",
    commonName: "Abdominal USS",
    category: "IMAGING",
    sampleType: "OTHER",
    fastingRequired: true,
    nigeriaWeighting: 80,
  },
  {
    loincCode: "IMG-USS-002",
    name: "Pelvic Ultrasound Scan",
    commonName: "Pelvic USS",
    category: "IMAGING",
    sampleType: "OTHER",
    fastingRequired: false,
    nigeriaWeighting: 78,
  },
  {
    loincCode: "IMG-USS-003",
    name: "Obstetric Ultrasound Scan",
    commonName: "Obstetric USS",
    category: "IMAGING",
    sampleType: "OTHER",
    fastingRequired: false,
    nigeriaWeighting: 80,
  },
  {
    loincCode: "IMG-USS-004",
    name: "Thyroid Ultrasound Scan",
    commonName: "Thyroid USS",
    category: "IMAGING",
    sampleType: "OTHER",
    fastingRequired: false,
    nigeriaWeighting: 65,
  },
  {
    loincCode: "IMG-USS-005",
    name: "Breast Ultrasound Scan",
    commonName: "Breast USS",
    category: "IMAGING",
    sampleType: "OTHER",
    fastingRequired: false,
    nigeriaWeighting: 68,
  },
  {
    loincCode: "IMG-USS-006",
    name: "Scrotal Ultrasound Scan",
    commonName: "Scrotal USS",
    category: "IMAGING",
    sampleType: "OTHER",
    fastingRequired: false,
    nigeriaWeighting: 58,
  },
  {
    loincCode: "IMG-USS-007",
    name: "Renal Ultrasound Scan",
    commonName: "Renal USS",
    category: "IMAGING",
    sampleType: "OTHER",
    fastingRequired: false,
    nigeriaWeighting: 72,
  },
  {
    loincCode: "IMG-USS-008",
    name: "Prostatic Ultrasound Scan (Transrectal)",
    commonName: "TRUS",
    category: "IMAGING",
    sampleType: "OTHER",
    fastingRequired: false,
    nigeriaWeighting: 58,
  },
  {
    loincCode: "IMG-ECHO-001",
    name: "Echocardiogram (Transthoracic)",
    commonName: "Echo / TTE",
    category: "IMAGING",
    sampleType: "OTHER",
    fastingRequired: false,
    nigeriaWeighting: 70,
  },
  {
    loincCode: "PROC-ECG-001",
    name: "Electrocardiogram (12-Lead)",
    commonName: "ECG",
    category: "IMAGING",
    sampleType: "OTHER",
    fastingRequired: false,
    nigeriaWeighting: 85,
  },
  {
    loincCode: "IMG-CT-001",
    name: "CT Scan Brain (Plain)",
    commonName: "CT brain",
    category: "IMAGING",
    sampleType: "OTHER",
    fastingRequired: false,
    nigeriaWeighting: 60,
  },
  {
    loincCode: "IMG-CT-002",
    name: "CT Scan Brain (With Contrast)",
    commonName: "CT brain + contrast",
    category: "IMAGING",
    sampleType: "OTHER",
    fastingRequired: true,
    nigeriaWeighting: 58,
  },
  {
    loincCode: "IMG-CT-003",
    name: "CT Scan Chest",
    commonName: "CT chest",
    category: "IMAGING",
    sampleType: "OTHER",
    fastingRequired: false,
    nigeriaWeighting: 55,
  },
  {
    loincCode: "IMG-CT-004",
    name: "CT Scan Abdomen and Pelvis",
    commonName: "CT abdomen/pelvis",
    category: "IMAGING",
    sampleType: "OTHER",
    fastingRequired: true,
    nigeriaWeighting: 55,
  },
  {
    loincCode: "IMG-CT-005",
    name: "CT Pulmonary Angiogram",
    commonName: "CTPA",
    category: "IMAGING",
    sampleType: "OTHER",
    fastingRequired: false,
    nigeriaWeighting: 50,
  },
  {
    loincCode: "IMG-MRI-001",
    name: "MRI Brain",
    commonName: null,
    category: "IMAGING",
    sampleType: "OTHER",
    fastingRequired: false,
    nigeriaWeighting: 55,
  },
  {
    loincCode: "IMG-MRI-002",
    name: "MRI Spine (Cervical)",
    commonName: null,
    category: "IMAGING",
    sampleType: "OTHER",
    fastingRequired: false,
    nigeriaWeighting: 52,
  },
  {
    loincCode: "IMG-MRI-003",
    name: "MRI Spine (Lumbar)",
    commonName: null,
    category: "IMAGING",
    sampleType: "OTHER",
    fastingRequired: false,
    nigeriaWeighting: 55,
  },
  {
    loincCode: "IMG-MRI-004",
    name: "MRI Knee",
    commonName: null,
    category: "IMAGING",
    sampleType: "OTHER",
    fastingRequired: false,
    nigeriaWeighting: 50,
  },
  {
    loincCode: "IMG-MAM-001",
    name: "Mammogram (Bilateral)",
    commonName: "Mammogram",
    category: "IMAGING",
    sampleType: "OTHER",
    fastingRequired: false,
    nigeriaWeighting: 60,
  },
  {
    loincCode: "IMG-DOP-001",
    name: "Doppler Ultrasound (Venous - Lower Limbs)",
    commonName: "Venous Doppler",
    category: "IMAGING",
    sampleType: "OTHER",
    fastingRequired: false,
    nigeriaWeighting: 62,
  },
  {
    loincCode: "IMG-DOP-002",
    name: "Doppler Ultrasound (Arterial - Lower Limbs)",
    commonName: "Arterial Doppler",
    category: "IMAGING",
    sampleType: "OTHER",
    fastingRequired: false,
    nigeriaWeighting: 58,
  },
  {
    loincCode: "IMG-DOP-003",
    name: "Carotid Doppler Ultrasound",
    commonName: "Carotid Doppler",
    category: "IMAGING",
    sampleType: "OTHER",
    fastingRequired: false,
    nigeriaWeighting: 55,
  },
  {
    loincCode: "IMG-BAR-001",
    name: "Barium Swallow",
    commonName: null,
    category: "IMAGING",
    sampleType: "OTHER",
    fastingRequired: true,
    nigeriaWeighting: 50,
  },
  {
    loincCode: "IMG-BAR-002",
    name: "Barium Meal",
    commonName: null,
    category: "IMAGING",
    sampleType: "OTHER",
    fastingRequired: true,
    nigeriaWeighting: 50,
  },
  {
    loincCode: "IMG-BAR-003",
    name: "Barium Enema",
    commonName: null,
    category: "IMAGING",
    sampleType: "OTHER",
    fastingRequired: true,
    nigeriaWeighting: 50,
  },
  {
    loincCode: "IMG-IVU-001",
    name: "Intravenous Urogram",
    commonName: "IVU",
    category: "IMAGING",
    sampleType: "OTHER",
    fastingRequired: true,
    nigeriaWeighting: 55,
  },
  {
    loincCode: "IMG-HSG-001",
    name: "Hysterosalpingogram",
    commonName: "HSG",
    category: "IMAGING",
    sampleType: "OTHER",
    fastingRequired: false,
    nigeriaWeighting: 62,
  },
  {
    loincCode: "PROC-EEG-001",
    name: "Electroencephalogram",
    commonName: "EEG",
    category: "IMAGING",
    sampleType: "OTHER",
    fastingRequired: false,
    nigeriaWeighting: 50,
  },
  {
    loincCode: "PROC-EMG-001",
    name: "Electromyography / Nerve Conduction Study",
    commonName: "EMG/NCS",
    category: "IMAGING",
    sampleType: "OTHER",
    fastingRequired: false,
    nigeriaWeighting: 45,
  },
  {
    loincCode: "PROC-SPIROM-001",
    name: "Spirometry (Pulmonary Function Test)",
    commonName: "PFT / Spirometry",
    category: "IMAGING",
    sampleType: "OTHER",
    fastingRequired: false,
    nigeriaWeighting: 55,
  },
  {
    loincCode: "IMG-DEXA-001",
    name: "DEXA Scan (Bone Densitometry)",
    commonName: "DEXA scan",
    category: "IMAGING",
    sampleType: "OTHER",
    fastingRequired: false,
    nigeriaWeighting: 45,
  },
];

export async function seedInvestigationCodes(prisma: PrismaClient) {
  console.log(`Seeding ${investigations.length} investigation codes...`);
  for (const inv of investigations) {
    await prisma.investigationCode.upsert({
      where: { loincCode: inv.loincCode },
      update: inv,
      create: inv,
    });
  }
  console.log('Investigation codes seeded.');
}
