import { PrismaClient } from "@prisma/client";

const drugs = [
  // ===== ANTIMALARIALS (NEML 2022) =====
  { genericName: "Artemether-Lumefantrine", brandNames: ["Coartem","Lonart","Amatem"], atcCode: "P01BF01", doseStrengths: ["20/120mg","80/480mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Twice daily x 3 days"], indication: "Uncomplicated malaria", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 100, isControlled: false },
  { genericName: "Artesunate", brandNames: ["Artesunat","Falcimon"], atcCode: "P01BE03", doseStrengths: ["50mg","60mg","120mg"], forms: ["Injection","Tablet"], routes: ["IV","IM","Oral"], frequencies: ["Once daily","Twice daily"], indication: "Severe malaria", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 98, isControlled: false },
  { genericName: "Amodiaquine", brandNames: ["Camoquin","Flavoquine"], atcCode: "P01BA06", doseStrengths: ["200mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Once daily x 3 days"], indication: "Uncomplicated malaria (with artesunate)", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 80, isControlled: false },
  { genericName: "Quinine", brandNames: ["Qualaquin"], atcCode: "P01BC01", doseStrengths: ["200mg","300mg","600mg/2ml"], forms: ["Tablet","Injection"], routes: ["Oral","IV"], frequencies: ["Three times daily"], indication: "Severe/complicated malaria", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 85, isControlled: false },
  { genericName: "Proguanil", brandNames: ["Paludrine"], atcCode: "P01BB01", doseStrengths: ["100mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Once daily"], indication: "Malaria prophylaxis", nigeriaAvailable: "LIMITED", esml: true, nigeriaWeighting: 50, isControlled: false },
  { genericName: "Sulfadoxine-Pyrimethamine", brandNames: ["Fansidar","Maloxine"], atcCode: "P01BD51", doseStrengths: ["500/25mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Single dose"], indication: "IPTp malaria prevention in pregnancy", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 85, isControlled: false },

  // ===== ANTIBIOTICS =====
  { genericName: "Amoxicillin", brandNames: ["Amoxil","Ospamox"], atcCode: "J01CA04", doseStrengths: ["250mg","500mg","125mg/5ml"], forms: ["Capsule","Suspension"], routes: ["Oral"], frequencies: ["Three times daily","Twice daily"], indication: "Bacterial infections", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 100, isControlled: false },
  { genericName: "Amoxicillin-Clavulanate", brandNames: ["Augmentin","Clavumox"], atcCode: "J01CR02", doseStrengths: ["375mg","625mg","1g","228mg/5ml","457mg/5ml"], forms: ["Tablet","Suspension"], routes: ["Oral"], frequencies: ["Twice daily","Three times daily"], indication: "Resistant bacterial infections", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 95, isControlled: false },
  { genericName: "Azithromycin", brandNames: ["Zithromax","Azee"], atcCode: "J01FA10", doseStrengths: ["250mg","500mg","200mg/5ml"], forms: ["Tablet","Capsule","Suspension"], routes: ["Oral"], frequencies: ["Once daily"], indication: "Respiratory/soft tissue infections", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 90, isControlled: false },
  { genericName: "Ciprofloxacin", brandNames: ["Ciproxin","Cipro"], atcCode: "J01MA02", doseStrengths: ["250mg","500mg","200mg/100ml"], forms: ["Tablet","Infusion"], routes: ["Oral","IV"], frequencies: ["Twice daily"], indication: "UTI, GI, bone & joint infections", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 90, isControlled: false },
  { genericName: "Levofloxacin", brandNames: ["Tavanic","Levaquin"], atcCode: "J01MA12", doseStrengths: ["250mg","500mg","750mg"], forms: ["Tablet","Infusion"], routes: ["Oral","IV"], frequencies: ["Once daily"], indication: "Respiratory, urinary infections", nigeriaAvailable: "WIDELY_AVAILABLE", esml: false, nigeriaWeighting: 75, isControlled: false },
  { genericName: "Metronidazole", brandNames: ["Flagyl","Metrogyl"], atcCode: "J01XD01", doseStrengths: ["200mg","400mg","500mg/100ml","200mg/5ml"], forms: ["Tablet","Infusion","Suspension"], routes: ["Oral","IV"], frequencies: ["Three times daily"], indication: "Anaerobic infections, amoebiasis", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 95, isControlled: false },
  { genericName: "Ceftriaxone", brandNames: ["Rocephin","Epicephin"], atcCode: "J01DD04", doseStrengths: ["250mg","500mg","1g","2g"], forms: ["Injection"], routes: ["IV","IM"], frequencies: ["Once daily","Twice daily"], indication: "Severe bacterial infections", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 90, isControlled: false },
  { genericName: "Cefuroxime", brandNames: ["Zinacef","Zinnat"], atcCode: "J01DC02", doseStrengths: ["250mg","500mg","750mg","1.5g"], forms: ["Tablet","Injection"], routes: ["Oral","IV","IM"], frequencies: ["Twice daily"], indication: "Respiratory, urinary, skin infections", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 80, isControlled: false },
  { genericName: "Cefixime", brandNames: ["Suprax","Cefspan"], atcCode: "J01DD08", doseStrengths: ["200mg","400mg","100mg/5ml"], forms: ["Capsule","Suspension"], routes: ["Oral"], frequencies: ["Once daily","Twice daily"], indication: "Respiratory, urinary infections, gonorrhoea", nigeriaAvailable: "WIDELY_AVAILABLE", esml: false, nigeriaWeighting: 75, isControlled: false },
  { genericName: "Erythromycin", brandNames: ["Erythrocin","Eryc"], atcCode: "J01FA01", doseStrengths: ["250mg","500mg","125mg/5ml"], forms: ["Tablet","Capsule","Suspension"], routes: ["Oral"], frequencies: ["Four times daily","Twice daily"], indication: "Penicillin allergy alternative, pertussis", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 70, isControlled: false },
  { genericName: "Doxycycline", brandNames: ["Vibramycin","Doxytet"], atcCode: "J01AA02", doseStrengths: ["100mg"], forms: ["Capsule","Tablet"], routes: ["Oral"], frequencies: ["Once daily","Twice daily"], indication: "Chlamydia, acne, malaria prophylaxis", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 85, isControlled: false },
  { genericName: "Gentamicin", brandNames: ["Garamycin"], atcCode: "J01GB03", doseStrengths: ["40mg/ml","80mg/2ml"], forms: ["Injection"], routes: ["IV","IM"], frequencies: ["Once daily","Three times daily"], indication: "Severe gram-negative infections", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 75, isControlled: false },
  { genericName: "Cloxacillin", brandNames: ["Orbenin"], atcCode: "J01CF02", doseStrengths: ["250mg","500mg"], forms: ["Capsule","Injection"], routes: ["Oral","IV","IM"], frequencies: ["Four times daily"], indication: "Staphylococcal infections", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 70, isControlled: false },
  { genericName: "Nitrofurantoin", brandNames: ["Macrodantin","Furadantin"], atcCode: "J01XE01", doseStrengths: ["50mg","100mg"], forms: ["Capsule"], routes: ["Oral"], frequencies: ["Four times daily","Twice daily"], indication: "Urinary tract infection", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 80, isControlled: false },
  { genericName: "Clarithromycin", brandNames: ["Klacid","Biaxin"], atcCode: "J01FA09", doseStrengths: ["250mg","500mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Twice daily"], indication: "H. pylori, respiratory infections", nigeriaAvailable: "WIDELY_AVAILABLE", esml: false, nigeriaWeighting: 65, isControlled: false },
  { genericName: "Tinidazole", brandNames: ["Fasigyn","Tindamax"], atcCode: "P01AB02", doseStrengths: ["500mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Once daily","Twice daily"], indication: "Giardiasis, amoebiasis, trichomoniasis", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 70, isControlled: false },
  { genericName: "Co-trimoxazole", brandNames: ["Septrin","Bactrim"], atcCode: "J01EE01", doseStrengths: ["480mg","960mg","240mg/5ml"], forms: ["Tablet","Suspension"], routes: ["Oral"], frequencies: ["Twice daily"], indication: "UTI, PCP prophylaxis in HIV", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 85, isControlled: false },
  { genericName: "Chloramphenicol", brandNames: ["Chloromycetin"], atcCode: "J01BA01", doseStrengths: ["250mg","1g"], forms: ["Capsule","Injection","Eye drop"], routes: ["Oral","IV","Topical"], frequencies: ["Four times daily"], indication: "Typhoid, bacterial meningitis, conjunctivitis", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 60, isControlled: false },
  { genericName: "Vancomycin", brandNames: ["Vancocin"], atcCode: "J01XA01", doseStrengths: ["500mg","1g"], forms: ["Injection"], routes: ["IV"], frequencies: ["Twice daily"], indication: "MRSA, C. diff (oral)", nigeriaAvailable: "LIMITED", esml: true, nigeriaWeighting: 50, isControlled: false },
  { genericName: "Meropenem", brandNames: ["Meronem"], atcCode: "J01DH02", doseStrengths: ["500mg","1g"], forms: ["Injection"], routes: ["IV"], frequencies: ["Three times daily"], indication: "Severe multi-drug resistant infections", nigeriaAvailable: "LIMITED", esml: true, nigeriaWeighting: 55, isControlled: false },

  // ===== ANTI-TUBERCULOSIS =====
  { genericName: "Isoniazid", brandNames: ["INH","Nydrazid"], atcCode: "J04AC01", doseStrengths: ["100mg","300mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Once daily"], indication: "Tuberculosis", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 85, isControlled: false },
  { genericName: "Rifampicin", brandNames: ["Rifadin","Rimactane"], atcCode: "J04AB02", doseStrengths: ["150mg","300mg","600mg"], forms: ["Capsule","Injection"], routes: ["Oral","IV"], frequencies: ["Once daily"], indication: "Tuberculosis", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 85, isControlled: false },
  { genericName: "Pyrazinamide", brandNames: ["Zinamide"], atcCode: "J04AK01", doseStrengths: ["400mg","500mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Once daily"], indication: "Tuberculosis (intensive phase)", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 80, isControlled: false },
  { genericName: "Ethambutol", brandNames: ["Myambutol"], atcCode: "J04AK02", doseStrengths: ["400mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Once daily"], indication: "Tuberculosis (intensive phase)", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 80, isControlled: false },
  { genericName: "RHZE (fixed-dose combination)", brandNames: ["Myrin-P","Rimstar-4"], atcCode: "J04AM06", doseStrengths: ["150/75/400/275mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Once daily"], indication: "Tuberculosis intensive phase", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 90, isControlled: false },
  { genericName: "RH (fixed-dose combination)", brandNames: ["Rifinah","Rimactazid"], atcCode: "J04AM02", doseStrengths: ["150/75mg","300/150mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Once daily"], indication: "Tuberculosis continuation phase", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 85, isControlled: false },

  // ===== ANTIRETROVIRALS (HIV) =====
  { genericName: "Tenofovir/Lamivudine/Dolutegravir (TLD)", brandNames: ["TLD"], atcCode: "J05AR27", doseStrengths: ["300/300/50mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Once daily"], indication: "HIV first-line treatment", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 95, isControlled: false },
  { genericName: "Tenofovir/Emtricitabine", brandNames: ["Truvada"], atcCode: "J05AR03", doseStrengths: ["300/200mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Once daily"], indication: "HIV, PrEP", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 85, isControlled: false },
  { genericName: "Dolutegravir", brandNames: ["Tivicay"], atcCode: "J05AJ03", doseStrengths: ["50mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Once daily"], indication: "HIV (integrase inhibitor)", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 85, isControlled: false },
  { genericName: "Efavirenz", brandNames: ["Sustiva","Stocrin"], atcCode: "J05AG03", doseStrengths: ["200mg","600mg"], forms: ["Tablet","Capsule"], routes: ["Oral"], frequencies: ["Once daily at bedtime"], indication: "HIV (NNRTI)", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 70, isControlled: false },
  { genericName: "Atazanavir/Ritonavir", brandNames: ["Reyataz/Norvir"], atcCode: "J05AR", doseStrengths: ["300/100mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Once daily"], indication: "HIV second-line (PI)", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 70, isControlled: false },
  { genericName: "Lopinavir/Ritonavir", brandNames: ["Aluvia","Kaletra"], atcCode: "J05AR10", doseStrengths: ["200/50mg","80/20mg per ml"], forms: ["Tablet","Solution"], routes: ["Oral"], frequencies: ["Twice daily"], indication: "HIV second-line paediatric", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 70, isControlled: false },
  { genericName: "Zidovudine (AZT)", brandNames: ["Retrovir","Zidovir"], atcCode: "J05AF01", doseStrengths: ["100mg","300mg","10mg/ml"], forms: ["Capsule","Tablet","Syrup"], routes: ["Oral"], frequencies: ["Twice daily"], indication: "HIV, PMTCT", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 65, isControlled: false },
  { genericName: "Nevirapine", brandNames: ["Viramune"], atcCode: "J05AG01", doseStrengths: ["200mg","50mg/5ml"], forms: ["Tablet","Suspension"], routes: ["Oral"], frequencies: ["Twice daily"], indication: "HIV, PMTCT", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 60, isControlled: false },
  { genericName: "Abacavir/Lamivudine", brandNames: ["Kivexa","Epzicom"], atcCode: "J05AR02", doseStrengths: ["600/300mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Once daily"], indication: "HIV backbone (HLA-B*5701 negative)", nigeriaAvailable: "LIMITED", esml: true, nigeriaWeighting: 55, isControlled: false },

  // ===== CARDIOVASCULAR =====
  { genericName: "Amlodipine", brandNames: ["Norvasc","Amlopine"], atcCode: "C08CA01", doseStrengths: ["2.5mg","5mg","10mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Once daily"], indication: "Hypertension, angina", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 100, isControlled: false },
  { genericName: "Lisinopril", brandNames: ["Zestril","Prinivil"], atcCode: "C09AA03", doseStrengths: ["2.5mg","5mg","10mg","20mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Once daily"], indication: "Hypertension, heart failure", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 90, isControlled: false },
  { genericName: "Losartan", brandNames: ["Cozaar","Lorzaar"], atcCode: "C09CA01", doseStrengths: ["25mg","50mg","100mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Once daily"], indication: "Hypertension (ACE-I intolerant)", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 85, isControlled: false },
  { genericName: "Atenolol", brandNames: ["Tenormin"], atcCode: "C07AB03", doseStrengths: ["25mg","50mg","100mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Once daily"], indication: "Hypertension, angina, arrhythmia", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 80, isControlled: false },
  { genericName: "Propranolol", brandNames: ["Inderal"], atcCode: "C07AA05", doseStrengths: ["10mg","40mg","80mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Two to three times daily"], indication: "Hypertension, tremor, thyrotoxicosis", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 75, isControlled: false },
  { genericName: "Nifedipine", brandNames: ["Adalat","Procardia"], atcCode: "C08CA05", doseStrengths: ["10mg","20mg","30mg","60mg"], forms: ["Tablet","Capsule"], routes: ["Oral"], frequencies: ["Once daily","Twice daily"], indication: "Hypertension, angina, Raynaud's", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 80, isControlled: false },
  { genericName: "Hydrochlorothiazide", brandNames: ["HCT","Esidrex"], atcCode: "C03AA03", doseStrengths: ["12.5mg","25mg","50mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Once daily"], indication: "Hypertension, oedema", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 85, isControlled: false },
  { genericName: "Furosemide", brandNames: ["Lasix"], atcCode: "C03CA01", doseStrengths: ["20mg","40mg","80mg","20mg/2ml"], forms: ["Tablet","Injection"], routes: ["Oral","IV","IM"], frequencies: ["Once daily","Twice daily"], indication: "Heart failure, oedema, hypertension", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 90, isControlled: false },
  { genericName: "Spironolactone", brandNames: ["Aldactone"], atcCode: "C03DA01", doseStrengths: ["25mg","50mg","100mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Once daily","Twice daily"], indication: "Heart failure, ascites, hypokalaemia", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 70, isControlled: false },
  { genericName: "Digoxin", brandNames: ["Lanoxin"], atcCode: "C01AA05", doseStrengths: ["0.0625mg","0.125mg","0.25mg"], forms: ["Tablet","Injection"], routes: ["Oral","IV"], frequencies: ["Once daily"], indication: "Heart failure, atrial fibrillation", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 65, isControlled: false },
  { genericName: "Aspirin", brandNames: ["Disprin","Aspro"], atcCode: "B01AC06", doseStrengths: ["75mg","100mg","300mg","600mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Once daily"], indication: "Antiplatelet, analgesia, anti-inflammatory", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 90, isControlled: false },
  { genericName: "Clopidogrel", brandNames: ["Plavix","Clopilet"], atcCode: "B01AC04", doseStrengths: ["75mg","300mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Once daily"], indication: "Antiplatelet (ACS, stroke)", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 70, isControlled: false },
  { genericName: "Warfarin", brandNames: ["Coumadin","Marevan"], atcCode: "B01AA03", doseStrengths: ["1mg","2mg","3mg","5mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Once daily"], indication: "Anticoagulation (AF, DVT, PE, prosthetic valves)", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 75, isControlled: false },
  { genericName: "Enoxaparin", brandNames: ["Clexane","Lovenox"], atcCode: "B01AB05", doseStrengths: ["20mg/0.2ml","40mg/0.4ml","60mg/0.6ml","80mg/0.8ml"], forms: ["Injection"], routes: ["SC"], frequencies: ["Once daily","Twice daily"], indication: "VTE prophylaxis and treatment", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 70, isControlled: false },
  { genericName: "Atorvastatin", brandNames: ["Lipitor","Atorva"], atcCode: "C10AA05", doseStrengths: ["10mg","20mg","40mg","80mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Once daily"], indication: "Dyslipidaemia, cardiovascular risk reduction", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 80, isControlled: false },
  { genericName: "Rosuvastatin", brandNames: ["Crestor"], atcCode: "C10AA07", doseStrengths: ["5mg","10mg","20mg","40mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Once daily"], indication: "Dyslipidaemia", nigeriaAvailable: "WIDELY_AVAILABLE", esml: false, nigeriaWeighting: 60, isControlled: false },
  { genericName: "Methyldopa", brandNames: ["Aldomet"], atcCode: "C02AB01", doseStrengths: ["250mg","500mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Two to three times daily"], indication: "Hypertension in pregnancy", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 75, isControlled: false },
  { genericName: "Hydralazine", brandNames: ["Apresoline"], atcCode: "C02DB02", doseStrengths: ["25mg","20mg/ml"], forms: ["Tablet","Injection"], routes: ["Oral","IV"], frequencies: ["Three times daily"], indication: "Hypertensive emergency, pre-eclampsia", nigeriaAvailable: "LIMITED", esml: true, nigeriaWeighting: 60, isControlled: false },

  // ===== DIABETES =====
  { genericName: "Metformin", brandNames: ["Glucophage","Diaformin"], atcCode: "A10BA02", doseStrengths: ["500mg","850mg","1000mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Twice daily","Three times daily"], indication: "Type 2 diabetes", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 95, isControlled: false },
  { genericName: "Glibenclamide", brandNames: ["Daonil","Euglucon"], atcCode: "A10BB01", doseStrengths: ["2.5mg","5mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Once daily","Twice daily"], indication: "Type 2 diabetes", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 80, isControlled: false },
  { genericName: "Glimepiride", brandNames: ["Amaryl"], atcCode: "A10BB12", doseStrengths: ["1mg","2mg","4mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Once daily"], indication: "Type 2 diabetes", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 75, isControlled: false },
  { genericName: "Insulin (Soluble/Regular)", brandNames: ["Humulin R","Actrapid"], atcCode: "A10AB01", doseStrengths: ["100IU/ml"], forms: ["Injection"], routes: ["SC","IV"], frequencies: ["Before meals","As directed"], indication: "Diabetes mellitus", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 85, isControlled: false },
  { genericName: "Insulin (NPH/Isophane)", brandNames: ["Humulin N","Insulatard"], atcCode: "A10AC01", doseStrengths: ["100IU/ml"], forms: ["Injection"], routes: ["SC"], frequencies: ["Once daily","Twice daily"], indication: "Diabetes mellitus", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 80, isControlled: false },
  { genericName: "Insulin (Pre-mixed 70/30)", brandNames: ["Humulin 70/30","Mixtard"], atcCode: "A10AD01", doseStrengths: ["100IU/ml"], forms: ["Injection"], routes: ["SC"], frequencies: ["Twice daily"], indication: "Diabetes mellitus", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 80, isControlled: false },
  { genericName: "Insulin Glargine", brandNames: ["Lantus","Basaglar"], atcCode: "A10AE04", doseStrengths: ["100IU/ml","300IU/ml"], forms: ["Injection"], routes: ["SC"], frequencies: ["Once daily"], indication: "Diabetes mellitus (basal)", nigeriaAvailable: "LIMITED", esml: false, nigeriaWeighting: 55, isControlled: false },
  { genericName: "Pioglitazone", brandNames: ["Actos","Pioglit"], atcCode: "A10BG03", doseStrengths: ["15mg","30mg","45mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Once daily"], indication: "Type 2 diabetes (insulin sensitiser)", nigeriaAvailable: "WIDELY_AVAILABLE", esml: false, nigeriaWeighting: 55, isControlled: false },
  { genericName: "Empagliflozin", brandNames: ["Jardiance"], atcCode: "A10BK03", doseStrengths: ["10mg","25mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Once daily"], indication: "Type 2 diabetes, heart failure", nigeriaAvailable: "LIMITED", esml: false, nigeriaWeighting: 45, isControlled: false },
  { genericName: "Sitagliptin", brandNames: ["Januvia"], atcCode: "A10BH01", doseStrengths: ["25mg","50mg","100mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Once daily"], indication: "Type 2 diabetes (DPP-4 inhibitor)", nigeriaAvailable: "LIMITED", esml: false, nigeriaWeighting: 40, isControlled: false },

  // ===== ANALGESICS & ANTI-INFLAMMATORY =====
  { genericName: "Paracetamol (Acetaminophen)", brandNames: ["Panadol","Tylenol","Emzor Paracetamol"], atcCode: "N02BE01", doseStrengths: ["120mg/5ml","250mg","500mg","1g","10mg/ml"], forms: ["Tablet","Syrup","Infusion","Suppository"], routes: ["Oral","IV","Rectal"], frequencies: ["Every 4-6 hours"], indication: "Pain, pyrexia", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 100, isControlled: false },
  { genericName: "Ibuprofen", brandNames: ["Brufen","Advil","Nurofen"], atcCode: "M01AE01", doseStrengths: ["200mg","400mg","600mg","100mg/5ml"], forms: ["Tablet","Suspension"], routes: ["Oral"], frequencies: ["Three times daily"], indication: "Pain, inflammation, pyrexia", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 90, isControlled: false },
  { genericName: "Diclofenac", brandNames: ["Voltaren","Cataflam","Olfen"], atcCode: "M01AB05", doseStrengths: ["25mg","50mg","75mg","100mg","75mg/3ml"], forms: ["Tablet","Capsule","Injection","Gel","Suppository"], routes: ["Oral","IM","Topical","Rectal"], frequencies: ["Two to three times daily"], indication: "Pain, inflammation, musculoskeletal", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 90, isControlled: false },
  { genericName: "Piroxicam", brandNames: ["Feldene","Brexidol"], atcCode: "M01AC01", doseStrengths: ["10mg","20mg"], forms: ["Capsule","Tablet"], routes: ["Oral"], frequencies: ["Once daily"], indication: "Musculoskeletal pain, arthritis", nigeriaAvailable: "WIDELY_AVAILABLE", esml: false, nigeriaWeighting: 70, isControlled: false },
  { genericName: "Tramadol", brandNames: ["Tramol","Ultram"], atcCode: "N02AX02", doseStrengths: ["50mg","100mg"], forms: ["Capsule","Injection"], routes: ["Oral","IV","IM"], frequencies: ["Every 4-6 hours"], indication: "Moderate to severe pain", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 75, isControlled: true, notes: "Schedule 2 controlled substance in Nigeria" },
  { genericName: "Morphine", brandNames: ["MST","Sevredol"], atcCode: "N02AA01", doseStrengths: ["10mg","15mg","30mg","10mg/ml"], forms: ["Tablet","Injection","Oral solution"], routes: ["Oral","IV","IM","SC"], frequencies: ["Every 4 hours","Every 12 hours (SR)"], indication: "Severe pain, palliative care", nigeriaAvailable: "LIMITED", esml: true, nigeriaWeighting: 60, isControlled: true, notes: "Schedule 1 narcotic" },
  { genericName: "Pentazocine", brandNames: ["Fortwin","Sosegon"], atcCode: "N02AD01", doseStrengths: ["25mg","30mg/ml"], forms: ["Tablet","Injection"], routes: ["Oral","IV","IM"], frequencies: ["Every 3-4 hours"], indication: "Moderate to severe pain", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 65, isControlled: true },
  { genericName: "Celecoxib", brandNames: ["Celebrex"], atcCode: "M01AH01", doseStrengths: ["100mg","200mg"], forms: ["Capsule"], routes: ["Oral"], frequencies: ["Once daily","Twice daily"], indication: "Osteoarthritis, rheumatoid arthritis", nigeriaAvailable: "WIDELY_AVAILABLE", esml: false, nigeriaWeighting: 55, isControlled: false },

  // ===== GASTROINTESTINAL =====
  { genericName: "Omeprazole", brandNames: ["Losec","Omez"], atcCode: "A02BC01", doseStrengths: ["10mg","20mg","40mg"], forms: ["Capsule","Injection"], routes: ["Oral","IV"], frequencies: ["Once daily","Twice daily"], indication: "GORD, peptic ulcer, H. pylori", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 95, isControlled: false },
  { genericName: "Esomeprazole", brandNames: ["Nexium"], atcCode: "A02BC05", doseStrengths: ["20mg","40mg"], forms: ["Tablet","Injection"], routes: ["Oral","IV"], frequencies: ["Once daily"], indication: "GORD, peptic ulcer", nigeriaAvailable: "WIDELY_AVAILABLE", esml: false, nigeriaWeighting: 70, isControlled: false },
  { genericName: "Ranitidine", brandNames: ["Zantac"], atcCode: "A02BA02", doseStrengths: ["150mg","300mg"], forms: ["Tablet","Injection"], routes: ["Oral","IV"], frequencies: ["Twice daily"], indication: "Peptic ulcer, GORD", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 70, isControlled: false, notes: "Availability may vary due to NDMA concerns" },
  { genericName: "Loperamide", brandNames: ["Imodium"], atcCode: "A07DA03", doseStrengths: ["2mg"], forms: ["Capsule","Tablet"], routes: ["Oral"], frequencies: ["After each loose stool"], indication: "Acute diarrhoea", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 70, isControlled: false },
  { genericName: "Oral Rehydration Salts (ORS)", brandNames: ["ORS","ORT"], atcCode: "A07CA", doseStrengths: ["Low-osmolarity sachet"], forms: ["Powder"], routes: ["Oral"], frequencies: ["After each stool"], indication: "Dehydration from diarrhoea", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 100, isControlled: false },
  { genericName: "Zinc Sulphate", brandNames: ["Zinkid","Zinvit"], atcCode: "A12CB01", doseStrengths: ["10mg","20mg"], forms: ["Tablet","Syrup"], routes: ["Oral"], frequencies: ["Once daily x 10-14 days"], indication: "Adjunct to ORS in diarrhoea (paediatric)", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 85, isControlled: false },
  { genericName: "Hyoscine Butylbromide", brandNames: ["Buscopan"], atcCode: "A03BB01", doseStrengths: ["10mg","20mg/ml"], forms: ["Tablet","Injection"], routes: ["Oral","IV","IM"], frequencies: ["Three times daily"], indication: "Abdominal cramps, IBS, renal colic", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 80, isControlled: false },
  { genericName: "Metoclopramide", brandNames: ["Maxolon","Plasil"], atcCode: "A03FA01", doseStrengths: ["10mg","5mg/ml"], forms: ["Tablet","Injection"], routes: ["Oral","IV","IM"], frequencies: ["Three times daily"], indication: "Nausea, vomiting, gastroparesis", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 80, isControlled: false },
  { genericName: "Ondansetron", brandNames: ["Zofran"], atcCode: "A04AA01", doseStrengths: ["4mg","8mg","4mg/2ml"], forms: ["Tablet","Injection"], routes: ["Oral","IV"], frequencies: ["Two to three times daily"], indication: "Nausea, vomiting (chemo, post-op)", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 75, isControlled: false },
  { genericName: "Magnesium Trisilicate", brandNames: ["Gaviscon","Gestid"], atcCode: "A02AD", doseStrengths: ["500mg","compound mixture"], forms: ["Tablet","Suspension"], routes: ["Oral"], frequencies: ["Three times daily"], indication: "Dyspepsia, hyperacidity", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 70, isControlled: false },

  // ===== RESPIRATORY =====
  { genericName: "Salbutamol (Albuterol)", brandNames: ["Ventolin","Asthalin"], atcCode: "R03AC02", doseStrengths: ["100mcg/puff","2mg","4mg","2mg/5ml","5mg/ml"], forms: ["MDI","Tablet","Syrup","Nebuliser solution"], routes: ["Inhaled","Oral"], frequencies: ["As needed","Three to four times daily"], indication: "Asthma, COPD", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 90, isControlled: false },
  { genericName: "Beclomethasone", brandNames: ["Becotide","Qvar"], atcCode: "R03BA01", doseStrengths: ["50mcg/puff","100mcg/puff","250mcg/puff"], forms: ["MDI"], routes: ["Inhaled"], frequencies: ["Twice daily"], indication: "Asthma (preventer)", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 80, isControlled: false },
  { genericName: "Budesonide", brandNames: ["Pulmicort"], atcCode: "R03BA02", doseStrengths: ["100mcg","200mcg","400mcg","0.5mg/2ml"], forms: ["MDI","DPI","Nebuliser"], routes: ["Inhaled"], frequencies: ["Twice daily"], indication: "Asthma (preventer)", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 70, isControlled: false },
  { genericName: "Fluticasone/Salmeterol", brandNames: ["Seretide","Advair"], atcCode: "R03AK06", doseStrengths: ["50/25mcg","125/25mcg","250/25mcg","50/100mcg","50/250mcg","50/500mcg"], forms: ["MDI","DPI"], routes: ["Inhaled"], frequencies: ["Twice daily"], indication: "Moderate-severe asthma, COPD", nigeriaAvailable: "WIDELY_AVAILABLE", esml: false, nigeriaWeighting: 65, isControlled: false },
  { genericName: "Ipratropium Bromide", brandNames: ["Atrovent"], atcCode: "R03BB01", doseStrengths: ["20mcg/puff","250mcg/ml","500mcg/ml"], forms: ["MDI","Nebuliser"], routes: ["Inhaled"], frequencies: ["Three to four times daily"], indication: "COPD, acute bronchospasm", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 60, isControlled: false },
  { genericName: "Prednisolone", brandNames: ["Prednisolone"], atcCode: "H02AB06", doseStrengths: ["1mg","5mg","15mg/5ml","25mg"], forms: ["Tablet","Syrup"], routes: ["Oral"], frequencies: ["Once daily"], indication: "Asthma exacerbation, autoimmune conditions", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 85, isControlled: false },
  { genericName: "Aminophylline", brandNames: ["Phyllocontin"], atcCode: "R03DA05", doseStrengths: ["100mg","225mg","250mg/10ml"], forms: ["Tablet","Injection"], routes: ["Oral","IV"], frequencies: ["Twice daily"], indication: "Severe acute asthma (IV), COPD", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 65, isControlled: false },

  // ===== ENDOCRINE (THYROID, STEROIDS) =====
  { genericName: "Levothyroxine", brandNames: ["Eltroxin","Euthyrox","Synthroid"], atcCode: "H03AA01", doseStrengths: ["25mcg","50mcg","100mcg","150mcg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Once daily"], indication: "Hypothyroidism", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 75, isControlled: false },
  { genericName: "Carbimazole", brandNames: ["Neo-Mercazole"], atcCode: "H03BB01", doseStrengths: ["5mg","10mg","20mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Two to three times daily"], indication: "Hyperthyroidism", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 65, isControlled: false },
  { genericName: "Dexamethasone", brandNames: ["Decadron","Dexona"], atcCode: "H02AB02", doseStrengths: ["0.5mg","4mg","4mg/ml","8mg/2ml"], forms: ["Tablet","Injection"], routes: ["Oral","IV","IM"], frequencies: ["Once daily","As directed"], indication: "Inflammation, cerebral oedema, shock", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 80, isControlled: false },
  { genericName: "Hydrocortisone", brandNames: ["Solu-Cortef","Efcorlin"], atcCode: "H02AB09", doseStrengths: ["10mg","20mg","100mg","250mg"], forms: ["Tablet","Injection"], routes: ["Oral","IV","IM"], frequencies: ["Two to three times daily"], indication: "Adrenal insufficiency, allergic reactions, shock", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 80, isControlled: false },

  // ===== PSYCHIATRY =====
  { genericName: "Amitriptyline", brandNames: ["Tryptanol","Elavil"], atcCode: "N06AA09", doseStrengths: ["10mg","25mg","50mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Once daily at bedtime"], indication: "Depression, neuropathic pain, insomnia", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 75, isControlled: false },
  { genericName: "Fluoxetine", brandNames: ["Prozac","Fluxetil"], atcCode: "N06AB03", doseStrengths: ["20mg","40mg"], forms: ["Capsule"], routes: ["Oral"], frequencies: ["Once daily"], indication: "Depression, OCD, anxiety", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 70, isControlled: false },
  { genericName: "Sertraline", brandNames: ["Zoloft"], atcCode: "N06AB06", doseStrengths: ["50mg","100mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Once daily"], indication: "Depression, anxiety, PTSD", nigeriaAvailable: "WIDELY_AVAILABLE", esml: false, nigeriaWeighting: 60, isControlled: false },
  { genericName: "Haloperidol", brandNames: ["Haldol","Serenace"], atcCode: "N05AD01", doseStrengths: ["0.5mg","1.5mg","5mg","5mg/ml"], forms: ["Tablet","Injection"], routes: ["Oral","IM"], frequencies: ["One to three times daily"], indication: "Psychosis, acute agitation, delirium", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 70, isControlled: false },
  { genericName: "Chlorpromazine", brandNames: ["Thorazine","Largactil"], atcCode: "N05AA01", doseStrengths: ["25mg","50mg","100mg","25mg/ml"], forms: ["Tablet","Injection"], routes: ["Oral","IM"], frequencies: ["Two to three times daily"], indication: "Psychosis, severe agitation", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 65, isControlled: false },
  { genericName: "Diazepam", brandNames: ["Valium"], atcCode: "N05BA01", doseStrengths: ["2mg","5mg","10mg","5mg/ml"], forms: ["Tablet","Injection"], routes: ["Oral","IV","IM","Rectal"], frequencies: ["Two to three times daily"], indication: "Anxiety, seizures, muscle spasm, alcohol withdrawal", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 75, isControlled: true, notes: "Schedule 4 controlled substance" },
  { genericName: "Carbamazepine", brandNames: ["Tegretol"], atcCode: "N03AF01", doseStrengths: ["100mg","200mg","400mg","100mg/5ml"], forms: ["Tablet","Syrup"], routes: ["Oral"], frequencies: ["Twice daily","Three times daily"], indication: "Epilepsy, trigeminal neuralgia, bipolar", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 75, isControlled: false },
  { genericName: "Sodium Valproate", brandNames: ["Epilim","Depakote"], atcCode: "N03AG01", doseStrengths: ["200mg","500mg","200mg/5ml","400mg/4ml"], forms: ["Tablet","Syrup","Injection"], routes: ["Oral","IV"], frequencies: ["Twice daily"], indication: "Epilepsy, bipolar, migraine prophylaxis", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 75, isControlled: false },
  { genericName: "Phenytoin", brandNames: ["Dilantin","Epanutin"], atcCode: "N03AB02", doseStrengths: ["50mg","100mg","50mg/ml"], forms: ["Capsule","Tablet","Injection"], routes: ["Oral","IV"], frequencies: ["Once daily","Two to three times daily"], indication: "Epilepsy, status epilepticus", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 70, isControlled: false },
  { genericName: "Risperidone", brandNames: ["Risperdal"], atcCode: "N05AX08", doseStrengths: ["1mg","2mg","3mg","4mg"], forms: ["Tablet","Oral solution"], routes: ["Oral"], frequencies: ["Once daily","Twice daily"], indication: "Schizophrenia, bipolar mania", nigeriaAvailable: "WIDELY_AVAILABLE", esml: false, nigeriaWeighting: 55, isControlled: false },
  { genericName: "Olanzapine", brandNames: ["Zyprexa"], atcCode: "N05AH03", doseStrengths: ["2.5mg","5mg","10mg","10mg"], forms: ["Tablet","Injection"], routes: ["Oral","IM"], frequencies: ["Once daily"], indication: "Schizophrenia, bipolar disorder", nigeriaAvailable: "LIMITED", esml: false, nigeriaWeighting: 45, isControlled: false },

  // ===== ANTIFUNGALS =====
  { genericName: "Fluconazole", brandNames: ["Diflucan","Fluzol"], atcCode: "J02AC01", doseStrengths: ["50mg","100mg","150mg","200mg","2mg/ml"], forms: ["Capsule","Infusion"], routes: ["Oral","IV"], frequencies: ["Once daily","Single dose"], indication: "Candidiasis, cryptococcal meningitis", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 80, isControlled: false },
  { genericName: "Ketoconazole", brandNames: ["Nizoral"], atcCode: "J02AB02", doseStrengths: ["200mg","2%"], forms: ["Tablet","Cream","Shampoo"], routes: ["Oral","Topical"], frequencies: ["Once daily"], indication: "Fungal skin infections, systemic mycoses", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 65, isControlled: false },
  { genericName: "Nystatin", brandNames: ["Mycostatin"], atcCode: "A07AA02", doseStrengths: ["100000IU/ml","100000IU"], forms: ["Oral suspension","Pessary","Cream"], routes: ["Oral","Vaginal","Topical"], frequencies: ["Four times daily"], indication: "Oral/vaginal candidiasis", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 70, isControlled: false },
  { genericName: "Clotrimazole", brandNames: ["Canesten","Mycelex"], atcCode: "G01AF02", doseStrengths: ["1%","100mg","200mg","500mg"], forms: ["Cream","Pessary"], routes: ["Topical","Vaginal"], frequencies: ["Once daily","Twice daily"], indication: "Vaginal candidiasis, dermatophytosis", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 75, isControlled: false },
  { genericName: "Griseofulvin", brandNames: ["Grisovin","Fulcin"], atcCode: "D01BA01", doseStrengths: ["125mg","250mg","500mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Once daily"], indication: "Dermatophyte infections (tinea)", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 60, isControlled: false },
  { genericName: "Terbinafine", brandNames: ["Lamisil"], atcCode: "D01BA02", doseStrengths: ["250mg","1%"], forms: ["Tablet","Cream"], routes: ["Oral","Topical"], frequencies: ["Once daily"], indication: "Onychomycosis, tinea", nigeriaAvailable: "WIDELY_AVAILABLE", esml: false, nigeriaWeighting: 50, isControlled: false },

  // ===== ANTIPARASITICS (HELMINTHS) =====
  { genericName: "Albendazole", brandNames: ["Zentel","Bendex"], atcCode: "P02CA03", doseStrengths: ["200mg","400mg"], forms: ["Tablet","Suspension"], routes: ["Oral"], frequencies: ["Single dose","Twice daily x 3 days"], indication: "Intestinal helminths, neurocysticercosis", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 90, isControlled: false },
  { genericName: "Mebendazole", brandNames: ["Vermox","Wormin"], atcCode: "P02CA01", doseStrengths: ["100mg","500mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Twice daily x 3 days","Single dose"], indication: "Intestinal worms", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 85, isControlled: false },
  { genericName: "Praziquantel", brandNames: ["Biltricide","Distocide"], atcCode: "P02BA01", doseStrengths: ["600mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Single dose","Three doses in one day"], indication: "Schistosomiasis, tapeworm", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 75, isControlled: false },
  { genericName: "Ivermectin", brandNames: ["Mectizan","Stromectol"], atcCode: "P02CF01", doseStrengths: ["3mg","6mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Single dose"], indication: "Onchocerciasis, strongyloides, scabies", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 80, isControlled: false },
  { genericName: "Permethrin", brandNames: ["Nix","Lyclear"], atcCode: "P03AC04", doseStrengths: ["1%","5%"], forms: ["Cream","Lotion"], routes: ["Topical"], frequencies: ["Single application"], indication: "Scabies, head lice", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 70, isControlled: false },
  { genericName: "Diethylcarbamazine", brandNames: ["Hetrazan","Banocide"], atcCode: "P02CB02", doseStrengths: ["50mg","100mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Three times daily x 12 days"], indication: "Lymphatic filariasis, loiasis", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 65, isControlled: false },

  // ===== OBSTETRICS & GYNAECOLOGY =====
  { genericName: "Oxytocin", brandNames: ["Pitocin","Syntocinon"], atcCode: "H01BB02", doseStrengths: ["5IU/ml","10IU/ml"], forms: ["Injection"], routes: ["IV","IM"], frequencies: ["As directed"], indication: "Labour induction, PPH prevention", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 85, isControlled: false },
  { genericName: "Misoprostol", brandNames: ["Cytotec"], atcCode: "A02BB01", doseStrengths: ["200mcg"], forms: ["Tablet"], routes: ["Oral","Sublingual","Rectal","Vaginal"], frequencies: ["As directed"], indication: "PPH prevention/treatment, cervical ripening", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 80, isControlled: false },
  { genericName: "Ergometrine", brandNames: ["Ergometrine Maleate"], atcCode: "G02AB03", doseStrengths: ["0.2mg","0.5mg/ml"], forms: ["Tablet","Injection"], routes: ["Oral","IV","IM"], frequencies: ["As directed"], indication: "PPH prevention and treatment", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 75, isControlled: false },
  { genericName: "Magnesium Sulphate", brandNames: ["MgSO4"], atcCode: "B05XA05", doseStrengths: ["50%","500mg/ml"], forms: ["Injection"], routes: ["IV","IM"], frequencies: ["Loading + maintenance"], indication: "Eclampsia, severe pre-eclampsia, tocolysis", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 85, isControlled: false },
  { genericName: "Ferrous Sulphate + Folic Acid", brandNames: ["Fefol","Astyfer"], atcCode: "B03AE01", doseStrengths: ["200mg/0.4mg","325mg/0.35mg"], forms: ["Tablet","Capsule"], routes: ["Oral"], frequencies: ["Once daily","Twice daily"], indication: "Iron-deficiency anaemia, pregnancy supplementation", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 95, isControlled: false },
  { genericName: "Combined Oral Contraceptive", brandNames: ["Microgynon","Lo-Femenal"], atcCode: "G03AA", doseStrengths: ["EE 30mcg/LNG 150mcg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Once daily"], indication: "Contraception", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 75, isControlled: false },
  { genericName: "Medroxyprogesterone Acetate (DMPA)", brandNames: ["Depo-Provera","Sayana Press"], atcCode: "G03AC06", doseStrengths: ["150mg/ml","104mg/0.65ml"], forms: ["Injection"], routes: ["IM","SC"], frequencies: ["Every 3 months"], indication: "Long-acting contraception", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 75, isControlled: false },
  { genericName: "Levonorgestrel (Emergency)", brandNames: ["Postinor-2","Plan B"], atcCode: "G03AC03", doseStrengths: ["0.75mg","1.5mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Single dose or 2 doses 12h apart"], indication: "Emergency contraception", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 70, isControlled: false },

  // ===== OPHTHALMOLOGY =====
  { genericName: "Chloramphenicol Eye Drops", brandNames: ["Chlorsig"], atcCode: "S01AA01", doseStrengths: ["0.5%"], forms: ["Eye drop"], routes: ["Topical (ophthalmic)"], frequencies: ["Every 2-6 hours"], indication: "Bacterial conjunctivitis", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 80, isControlled: false },
  { genericName: "Timolol Eye Drops", brandNames: ["Timoptol","Nyogel"], atcCode: "S01ED01", doseStrengths: ["0.25%","0.5%"], forms: ["Eye drop"], routes: ["Topical (ophthalmic)"], frequencies: ["Twice daily"], indication: "Glaucoma, ocular hypertension", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 65, isControlled: false },
  { genericName: "Pilocarpine Eye Drops", brandNames: ["Pilogel"], atcCode: "S01EB01", doseStrengths: ["1%","2%","4%"], forms: ["Eye drop"], routes: ["Topical (ophthalmic)"], frequencies: ["Three to four times daily"], indication: "Glaucoma", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 55, isControlled: false },
  { genericName: "Tetracaine Eye Drops", brandNames: ["Minims Amethocaine"], atcCode: "S01HA03", doseStrengths: ["0.5%","1%"], forms: ["Eye drop"], routes: ["Topical (ophthalmic)"], frequencies: ["As needed"], indication: "Topical ocular anaesthesia", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 50, isControlled: false },

  // ===== DERMATOLOGY =====
  { genericName: "Hydrocortisone Cream", brandNames: ["Dakacort","HC45"], atcCode: "D07AA02", doseStrengths: ["0.5%","1%"], forms: ["Cream","Ointment"], routes: ["Topical"], frequencies: ["Twice daily"], indication: "Eczema, dermatitis, insect bites", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 70, isControlled: false },
  { genericName: "Betamethasone Cream", brandNames: ["Betnovate","Celestoderm"], atcCode: "D07AC01", doseStrengths: ["0.025%","0.05%","0.1%"], forms: ["Cream","Ointment"], routes: ["Topical"], frequencies: ["Once to twice daily"], indication: "Severe eczema, psoriasis", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 70, isControlled: false },
  { genericName: "Calamine Lotion", brandNames: ["Calamine"], atcCode: "D02AB", doseStrengths: ["15%"], forms: ["Lotion"], routes: ["Topical"], frequencies: ["As needed"], indication: "Pruritus, sunburn, insect bites", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 65, isControlled: false },
  { genericName: "Silver Sulfadiazine", brandNames: ["Flamazine","Silvadene"], atcCode: "D06BA01", doseStrengths: ["1%"], forms: ["Cream"], routes: ["Topical"], frequencies: ["Once to twice daily"], indication: "Burns, wound infections", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 60, isControlled: false },
  { genericName: "Whitfield's Ointment", brandNames: ["Whitfield's"], atcCode: "D01AA", doseStrengths: ["Compound"], forms: ["Ointment"], routes: ["Topical"], frequencies: ["Twice daily"], indication: "Fungal skin infections (tinea)", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 65, isControlled: false },
  { genericName: "Benzoyl Peroxide", brandNames: ["Benzac","PanOxyl"], atcCode: "D10AE01", doseStrengths: ["2.5%","5%","10%"], forms: ["Gel","Cream","Wash"], routes: ["Topical"], frequencies: ["Once to twice daily"], indication: "Acne vulgaris", nigeriaAvailable: "WIDELY_AVAILABLE", esml: false, nigeriaWeighting: 50, isControlled: false },

  // ===== ALLERGY & ANTIHISTAMINES =====
  { genericName: "Cetirizine", brandNames: ["Zyrtec","Allercet"], atcCode: "R06AE07", doseStrengths: ["5mg","10mg","5mg/5ml"], forms: ["Tablet","Syrup"], routes: ["Oral"], frequencies: ["Once daily"], indication: "Allergic rhinitis, urticaria", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 80, isControlled: false },
  { genericName: "Loratadine", brandNames: ["Claritin","Loraday"], atcCode: "R06AX13", doseStrengths: ["10mg","5mg/5ml"], forms: ["Tablet","Syrup"], routes: ["Oral"], frequencies: ["Once daily"], indication: "Allergic rhinitis, urticaria", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 80, isControlled: false },
  { genericName: "Chlorpheniramine", brandNames: ["Piriton","Chlor-Trimeton"], atcCode: "R06AB04", doseStrengths: ["2mg","4mg","2mg/5ml","10mg/ml"], forms: ["Tablet","Syrup","Injection"], routes: ["Oral","IV","IM"], frequencies: ["Three times daily"], indication: "Allergic reactions, urticaria, rhinitis", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 85, isControlled: false },
  { genericName: "Promethazine", brandNames: ["Phenergan","Avomine"], atcCode: "R06AD02", doseStrengths: ["10mg","25mg","25mg/ml","5mg/5ml"], forms: ["Tablet","Injection","Syrup"], routes: ["Oral","IM","IV"], frequencies: ["Two to three times daily"], indication: "Allergy, motion sickness, sedation", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 75, isControlled: false },
  { genericName: "Epinephrine (Adrenaline)", brandNames: ["EpiPen","Adrenaline"], atcCode: "C01CA24", doseStrengths: ["1:1000 (1mg/ml)","1:10000"], forms: ["Injection"], routes: ["IM","IV","SC"], frequencies: ["As needed in emergency"], indication: "Anaphylaxis, cardiac arrest", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 85, isControlled: false },

  // ===== VITAMINS & SUPPLEMENTS =====
  { genericName: "Folic Acid", brandNames: ["Folvite"], atcCode: "B03BB01", doseStrengths: ["400mcg","5mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Once daily"], indication: "Megaloblastic anaemia, pregnancy, methotrexate rescue", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 90, isControlled: false },
  { genericName: "Vitamin B Complex", brandNames: ["Becosules","Neurobion"], atcCode: "A11EA", doseStrengths: ["Various"], forms: ["Tablet","Injection"], routes: ["Oral","IM"], frequencies: ["Once daily"], indication: "B-vitamin deficiency", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 75, isControlled: false },
  { genericName: "Vitamin C (Ascorbic Acid)", brandNames: ["Cebion","Vitasorbic"], atcCode: "A11GA01", doseStrengths: ["100mg","250mg","500mg","1000mg"], forms: ["Tablet","Chewable"], routes: ["Oral"], frequencies: ["Once daily"], indication: "Vitamin C deficiency, immune support", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 75, isControlled: false },
  { genericName: "Vitamin A", brandNames: ["Arovit"], atcCode: "A11CA01", doseStrengths: ["100000IU","200000IU"], forms: ["Capsule","Solution"], routes: ["Oral"], frequencies: ["Single dose (supplementation)"], indication: "Vitamin A deficiency, measles adjunct", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 80, isControlled: false },
  { genericName: "Calcium + Vitamin D", brandNames: ["Caltrate","Calcichew D3"], atcCode: "A12AX", doseStrengths: ["500mg/400IU","600mg/200IU"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Once daily","Twice daily"], indication: "Osteoporosis prevention, calcium supplementation", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 60, isControlled: false },

  // ===== EMERGENCY / ANAESTHESIA =====
  { genericName: "Atropine", brandNames: ["Atropine Sulphate"], atcCode: "A03BA01", doseStrengths: ["0.6mg/ml","1mg/ml"], forms: ["Injection"], routes: ["IV","IM","SC"], frequencies: ["As directed"], indication: "Bradycardia, organophosphate poisoning, pre-anaesthesia", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 70, isControlled: false },
  { genericName: "Lidocaine (Lignocaine)", brandNames: ["Xylocaine"], atcCode: "N01BB02", doseStrengths: ["1%","2%","2% + Adrenaline"], forms: ["Injection","Jelly","Spray"], routes: ["Local infiltration","Topical"], frequencies: ["As needed"], indication: "Local anaesthesia, ventricular arrhythmia", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 85, isControlled: false },
  { genericName: "Ketamine", brandNames: ["Ketalar"], atcCode: "N01AX03", doseStrengths: ["10mg/ml","50mg/ml","100mg/ml"], forms: ["Injection"], routes: ["IV","IM"], frequencies: ["As directed"], indication: "Dissociative anaesthesia, procedural sedation", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 65, isControlled: true, notes: "Schedule 2 controlled substance" },
  { genericName: "Propofol", brandNames: ["Diprivan"], atcCode: "N01AX10", doseStrengths: ["10mg/ml","20mg/ml"], forms: ["Injection"], routes: ["IV"], frequencies: ["As directed"], indication: "General anaesthesia induction/maintenance", nigeriaAvailable: "LIMITED", esml: true, nigeriaWeighting: 55, isControlled: false },
  { genericName: "Thiopental", brandNames: ["Pentothal"], atcCode: "N01AF03", doseStrengths: ["500mg","1g"], forms: ["Injection"], routes: ["IV"], frequencies: ["Single induction dose"], indication: "Anaesthesia induction, status epilepticus", nigeriaAvailable: "LIMITED", esml: true, nigeriaWeighting: 50, isControlled: true },
  { genericName: "Suxamethonium (Succinylcholine)", brandNames: ["Scoline","Anectine"], atcCode: "M03AB01", doseStrengths: ["50mg/ml","100mg/2ml"], forms: ["Injection"], routes: ["IV"], frequencies: ["Single dose"], indication: "Rapid sequence intubation", nigeriaAvailable: "LIMITED", esml: true, nigeriaWeighting: 50, isControlled: false },
  { genericName: "Neostigmine", brandNames: ["Prostigmin"], atcCode: "N07AA01", doseStrengths: ["0.5mg/ml","2.5mg/ml"], forms: ["Injection"], routes: ["IV","IM"], frequencies: ["As directed"], indication: "Reversal of neuromuscular blockade, myasthenia gravis", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 50, isControlled: false },

  // ===== IV FLUIDS & ELECTROLYTES =====
  { genericName: "Normal Saline (0.9% NaCl)", brandNames: ["NS"], atcCode: "B05BB01", doseStrengths: ["500ml","1000ml"], forms: ["Infusion"], routes: ["IV"], frequencies: ["As directed"], indication: "Volume replacement, dehydration", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 95, isControlled: false },
  { genericName: "Ringer's Lactate", brandNames: ["Hartmann's Solution"], atcCode: "B05BB01", doseStrengths: ["500ml","1000ml"], forms: ["Infusion"], routes: ["IV"], frequencies: ["As directed"], indication: "Volume replacement, burns, surgical fluid", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 90, isControlled: false },
  { genericName: "5% Dextrose", brandNames: ["D5W"], atcCode: "B05BA03", doseStrengths: ["500ml","1000ml"], forms: ["Infusion"], routes: ["IV"], frequencies: ["As directed"], indication: "Hypoglycaemia, hydration, drug dilution", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 90, isControlled: false },
  { genericName: "Dextrose Saline", brandNames: ["DNS"], atcCode: "B05BB02", doseStrengths: ["500ml","1000ml"], forms: ["Infusion"], routes: ["IV"], frequencies: ["As directed"], indication: "Maintenance fluid", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 85, isControlled: false },
  { genericName: "Potassium Chloride", brandNames: ["KCl","Slow-K"], atcCode: "A12BA01", doseStrengths: ["600mg","15%"], forms: ["Tablet","Injection"], routes: ["Oral","IV (diluted)"], frequencies: ["As directed"], indication: "Hypokalaemia", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 70, isControlled: false },

  // ===== ANTIHELMINTHIC / TROPICAL =====
  { genericName: "Artemisinin-based Combination (ACT)", brandNames: ["ACT","Coartem"], atcCode: "P01BF", doseStrengths: ["Various"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Twice daily x 3 days"], indication: "Uncomplicated malaria (WHO recommended)", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 95, isControlled: false },

  // ===== ANTICONVULSANTS =====
  { genericName: "Levetiracetam", brandNames: ["Keppra"], atcCode: "N03AX14", doseStrengths: ["250mg","500mg","750mg","1000mg","100mg/ml"], forms: ["Tablet","Oral solution","Injection"], routes: ["Oral","IV"], frequencies: ["Twice daily"], indication: "Epilepsy (focal, generalised)", nigeriaAvailable: "LIMITED", esml: false, nigeriaWeighting: 45, isControlled: false },
  { genericName: "Phenobarbitone", brandNames: ["Luminal","Gardenal"], atcCode: "N03AA02", doseStrengths: ["15mg","30mg","60mg","200mg/ml"], forms: ["Tablet","Injection"], routes: ["Oral","IV","IM"], frequencies: ["Once daily at bedtime"], indication: "Epilepsy, neonatal seizures, status epilepticus", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 65, isControlled: true, notes: "Schedule 4 controlled substance" },

  // ===== MISCELLANEOUS =====
  { genericName: "Methotrexate", brandNames: ["Trexall"], atcCode: "L01BA01", doseStrengths: ["2.5mg","10mg","25mg/ml"], forms: ["Tablet","Injection"], routes: ["Oral","IM","SC"], frequencies: ["Once weekly"], indication: "Rheumatoid arthritis, psoriasis, ectopic pregnancy", nigeriaAvailable: "LIMITED", esml: true, nigeriaWeighting: 55, isControlled: false },
  { genericName: "Allopurinol", brandNames: ["Zyloric","Zyloprim"], atcCode: "M04AA01", doseStrengths: ["100mg","300mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Once daily"], indication: "Gout, hyperuricaemia", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 65, isControlled: false },
  { genericName: "Colchicine", brandNames: ["Colchicine"], atcCode: "M04AC01", doseStrengths: ["0.5mg","1mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Two to three times daily (acute)"], indication: "Acute gout, FMF", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 55, isControlled: false },
  { genericName: "Hydroxychloroquine", brandNames: ["Plaquenil"], atcCode: "P01BA02", doseStrengths: ["200mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Once daily","Twice daily"], indication: "SLE, rheumatoid arthritis", nigeriaAvailable: "WIDELY_AVAILABLE", esml: false, nigeriaWeighting: 55, isControlled: false },
  { genericName: "Tranexamic Acid", brandNames: ["Cyklokapron","Lysteda"], atcCode: "B02AA02", doseStrengths: ["500mg","100mg/ml"], forms: ["Tablet","Injection"], routes: ["Oral","IV"], frequencies: ["Two to three times daily"], indication: "Heavy menstrual bleeding, trauma haemorrhage", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 65, isControlled: false },
  { genericName: "Vitamin K (Phytomenadione)", brandNames: ["Konakion"], atcCode: "B02BA01", doseStrengths: ["1mg","10mg","10mg/ml"], forms: ["Tablet","Injection"], routes: ["Oral","IV","IM"], frequencies: ["Single dose","As directed"], indication: "Warfarin reversal, neonatal prophylaxis, coagulopathy", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 70, isControlled: false },
  { genericName: "Activated Charcoal", brandNames: ["Carbomix","Ultracarbon"], atcCode: "A07BA01", doseStrengths: ["50g","25g"], forms: ["Powder","Suspension"], routes: ["Oral"], frequencies: ["Single dose"], indication: "Acute poisoning (within 1 hour)", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 60, isControlled: false },
  { genericName: "N-Acetylcysteine", brandNames: ["Parvolex","Fluimucil"], atcCode: "V03AB23", doseStrengths: ["200mg/ml","600mg"], forms: ["Injection","Tablet","Sachet"], routes: ["IV","Oral"], frequencies: ["As per protocol"], indication: "Paracetamol overdose, mucolytic", nigeriaAvailable: "LIMITED", esml: true, nigeriaWeighting: 55, isControlled: false },
  { genericName: "Mannitol", brandNames: ["Osmitrol"], atcCode: "B05BC01", doseStrengths: ["10%","20%"], forms: ["Infusion"], routes: ["IV"], frequencies: ["As directed"], indication: "Cerebral oedema, acute glaucoma, raised ICP", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 60, isControlled: false },
  { genericName: "Chlorhexidine", brandNames: ["Savlon","Hibitane"], atcCode: "D08AC02", doseStrengths: ["0.5%","2%","4%","5%"], forms: ["Solution","Gel"], routes: ["Topical"], frequencies: ["As needed"], indication: "Skin antisepsis, surgical scrub, cord care", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 75, isControlled: false },
  { genericName: "Povidone-Iodine", brandNames: ["Betadine","Wokadine"], atcCode: "D08AG02", doseStrengths: ["5%","10%"], forms: ["Solution","Ointment","Scrub"], routes: ["Topical"], frequencies: ["As needed"], indication: "Wound antisepsis, surgical preparation", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 75, isControlled: false },
  { genericName: "Tetanus Toxoid", brandNames: ["TT"], atcCode: "J07AM01", doseStrengths: ["40IU/0.5ml"], forms: ["Injection"], routes: ["IM"], frequencies: ["Per immunisation schedule"], indication: "Tetanus prophylaxis, wound management", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 80, isControlled: false },
  { genericName: "Anti-Tetanus Serum (ATS)", brandNames: ["ATS"], atcCode: "J06AA02", doseStrengths: ["1500IU","3000IU"], forms: ["Injection"], routes: ["IM"], frequencies: ["Single dose"], indication: "Tetanus treatment/post-exposure prophylaxis", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 70, isControlled: false },
  { genericName: "Anti-Snake Venom", brandNames: ["ASVS","Polyvalent"], atcCode: "J06AA03", doseStrengths: ["10ml vial"], forms: ["Injection"], routes: ["IV"], frequencies: ["As directed"], indication: "Snake envenomation", nigeriaAvailable: "LIMITED", esml: true, nigeriaWeighting: 60, isControlled: false },
  { genericName: "Dopamine", brandNames: ["Intropin"], atcCode: "C01CA04", doseStrengths: ["40mg/ml","80mg/ml","200mg/5ml"], forms: ["Injection"], routes: ["IV infusion"], frequencies: ["Continuous infusion"], indication: "Cardiogenic/septic shock, low cardiac output", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 60, isControlled: false },
  { genericName: "Dobutamine", brandNames: ["Dobutrex"], atcCode: "C01CA07", doseStrengths: ["250mg/20ml"], forms: ["Injection"], routes: ["IV infusion"], frequencies: ["Continuous infusion"], indication: "Acute heart failure, cardiogenic shock", nigeriaAvailable: "LIMITED", esml: true, nigeriaWeighting: 50, isControlled: false },

  // ===== ONCOLOGY / CYTOTOXICS =====
  { genericName: "Cyclophosphamide", brandNames: ["Endoxan","Cytoxan"], atcCode: "L01AA01", doseStrengths: ["50mg","200mg","500mg","1g"], forms: ["Tablet","Injection"], routes: ["Oral","IV"], frequencies: ["As per protocol"], indication: "Lymphoma, leukaemia, autoimmune diseases", nigeriaAvailable: "LIMITED", esml: true, nigeriaWeighting: 55, isControlled: false },
  { genericName: "Cisplatin", brandNames: ["Platinol"], atcCode: "L01XA01", doseStrengths: ["10mg","50mg","100mg"], forms: ["Injection"], routes: ["IV"], frequencies: ["As per protocol"], indication: "Solid tumours (cervical, ovarian, lung)", nigeriaAvailable: "LIMITED", esml: true, nigeriaWeighting: 50, isControlled: false },
  { genericName: "Carboplatin", brandNames: ["Paraplatin"], atcCode: "L01XA02", doseStrengths: ["150mg","450mg"], forms: ["Injection"], routes: ["IV"], frequencies: ["As per protocol"], indication: "Ovarian, lung, head & neck cancers", nigeriaAvailable: "LIMITED", esml: true, nigeriaWeighting: 45, isControlled: false },
  { genericName: "5-Fluorouracil", brandNames: ["Adrucil","Efudex"], atcCode: "L01BC02", doseStrengths: ["250mg/5ml","500mg/10ml","5%"], forms: ["Injection","Cream"], routes: ["IV","Topical"], frequencies: ["As per protocol"], indication: "GI cancers, breast cancer, skin cancers", nigeriaAvailable: "LIMITED", esml: true, nigeriaWeighting: 50, isControlled: false },
  { genericName: "Doxorubicin", brandNames: ["Adriamycin"], atcCode: "L01DB01", doseStrengths: ["10mg","50mg"], forms: ["Injection"], routes: ["IV"], frequencies: ["As per protocol"], indication: "Breast cancer, lymphoma, sarcoma", nigeriaAvailable: "LIMITED", esml: true, nigeriaWeighting: 50, isControlled: false },
  { genericName: "Vincristine", brandNames: ["Oncovin"], atcCode: "L01CA02", doseStrengths: ["1mg/ml","2mg/2ml"], forms: ["Injection"], routes: ["IV"], frequencies: ["As per protocol"], indication: "Leukaemia, lymphoma, nephroblastoma", nigeriaAvailable: "LIMITED", esml: true, nigeriaWeighting: 45, isControlled: false },
  { genericName: "Bleomycin", brandNames: ["Blenoxane"], atcCode: "L01DC01", doseStrengths: ["15IU"], forms: ["Injection"], routes: ["IV","IM","SC"], frequencies: ["As per protocol"], indication: "Hodgkin lymphoma, testicular cancer", nigeriaAvailable: "LIMITED", esml: true, nigeriaWeighting: 40, isControlled: false },
  { genericName: "Tamoxifen", brandNames: ["Nolvadex"], atcCode: "L02BA01", doseStrengths: ["10mg","20mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Once daily"], indication: "Breast cancer (ER+)", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 60, isControlled: false },
  { genericName: "Imatinib", brandNames: ["Gleevec","Glivec"], atcCode: "L01EA01", doseStrengths: ["100mg","400mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Once daily"], indication: "CML, GIST", nigeriaAvailable: "LIMITED", esml: false, nigeriaWeighting: 40, isControlled: false },
  { genericName: "Capecitabine", brandNames: ["Xeloda"], atcCode: "L01BC06", doseStrengths: ["150mg","500mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Twice daily x 14 days"], indication: "Breast, colorectal cancer", nigeriaAvailable: "LIMITED", esml: false, nigeriaWeighting: 40, isControlled: false },

  // ===== UROLOGY / PROSTATE =====
  { genericName: "Tamsulosin", brandNames: ["Flomax","Omnic"], atcCode: "G04CA02", doseStrengths: ["0.2mg","0.4mg"], forms: ["Capsule","Tablet"], routes: ["Oral"], frequencies: ["Once daily"], indication: "BPH, lower urinary tract symptoms", nigeriaAvailable: "WIDELY_AVAILABLE", esml: false, nigeriaWeighting: 65, isControlled: false },
  { genericName: "Finasteride", brandNames: ["Proscar","Propecia"], atcCode: "G04CB01", doseStrengths: ["1mg","5mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Once daily"], indication: "BPH, male pattern baldness", nigeriaAvailable: "WIDELY_AVAILABLE", esml: false, nigeriaWeighting: 55, isControlled: false },
  { genericName: "Dutasteride", brandNames: ["Avodart"], atcCode: "G04CB02", doseStrengths: ["0.5mg"], forms: ["Capsule"], routes: ["Oral"], frequencies: ["Once daily"], indication: "BPH", nigeriaAvailable: "LIMITED", esml: false, nigeriaWeighting: 40, isControlled: false },
  { genericName: "Sildenafil", brandNames: ["Viagra","Manforce"], atcCode: "G04BE03", doseStrengths: ["25mg","50mg","100mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["As needed"], indication: "Erectile dysfunction, pulmonary hypertension", nigeriaAvailable: "WIDELY_AVAILABLE", esml: false, nigeriaWeighting: 55, isControlled: false },
  { genericName: "Oxybutynin", brandNames: ["Ditropan"], atcCode: "G04BD04", doseStrengths: ["2.5mg","5mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Two to three times daily"], indication: "Overactive bladder, urge incontinence", nigeriaAvailable: "LIMITED", esml: false, nigeriaWeighting: 35, isControlled: false },

  // ===== NEWER ANTICOAGULANTS =====
  { genericName: "Rivaroxaban", brandNames: ["Xarelto"], atcCode: "B01AF01", doseStrengths: ["2.5mg","10mg","15mg","20mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Once daily","Twice daily"], indication: "VTE, AF stroke prevention", nigeriaAvailable: "WIDELY_AVAILABLE", esml: false, nigeriaWeighting: 55, isControlled: false },
  { genericName: "Apixaban", brandNames: ["Eliquis"], atcCode: "B01AF02", doseStrengths: ["2.5mg","5mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Twice daily"], indication: "VTE, AF stroke prevention", nigeriaAvailable: "LIMITED", esml: false, nigeriaWeighting: 45, isControlled: false },
  { genericName: "Heparin (Unfractionated)", brandNames: ["Heparin"], atcCode: "B01AB01", doseStrengths: ["1000IU/ml","5000IU/ml","25000IU/5ml"], forms: ["Injection"], routes: ["IV","SC"], frequencies: ["Continuous infusion or every 8-12 hours"], indication: "Anticoagulation (DVT, PE, ACS, dialysis)", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 75, isControlled: false },

  // ===== MUSCLE RELAXANTS =====
  { genericName: "Baclofen", brandNames: ["Lioresal"], atcCode: "M03BX01", doseStrengths: ["10mg","25mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Three times daily"], indication: "Spasticity (spinal cord injury, MS)", nigeriaAvailable: "WIDELY_AVAILABLE", esml: false, nigeriaWeighting: 45, isControlled: false },
  { genericName: "Tizanidine", brandNames: ["Zanaflex","Sirdalud"], atcCode: "M03BX02", doseStrengths: ["2mg","4mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Three times daily"], indication: "Muscle spasm, spasticity", nigeriaAvailable: "WIDELY_AVAILABLE", esml: false, nigeriaWeighting: 40, isControlled: false },
  { genericName: "Orphenadrine", brandNames: ["Norflex","Disipal"], atcCode: "M03BC01", doseStrengths: ["50mg","100mg"], forms: ["Tablet","Injection"], routes: ["Oral","IM","IV"], frequencies: ["Twice daily"], indication: "Muscle spasm, acute musculoskeletal pain", nigeriaAvailable: "WIDELY_AVAILABLE", esml: false, nigeriaWeighting: 50, isControlled: false },

  // ===== ANTIDIABETIC COMBINATIONS =====
  { genericName: "Metformin/Glimepiride", brandNames: ["Amaryl M","Glimy-M"], atcCode: "A10BD02", doseStrengths: ["500/1mg","500/2mg","1000/2mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Once daily","Twice daily"], indication: "Type 2 diabetes (dual therapy)", nigeriaAvailable: "WIDELY_AVAILABLE", esml: false, nigeriaWeighting: 65, isControlled: false },
  { genericName: "Metformin/Sitagliptin", brandNames: ["Janumet"], atcCode: "A10BD07", doseStrengths: ["500/50mg","1000/50mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Twice daily"], indication: "Type 2 diabetes (dual therapy)", nigeriaAvailable: "LIMITED", esml: false, nigeriaWeighting: 40, isControlled: false },
  { genericName: "Gliclazide", brandNames: ["Diamicron"], atcCode: "A10BB09", doseStrengths: ["30mg","60mg","80mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Once daily","Twice daily"], indication: "Type 2 diabetes", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 70, isControlled: false },

  // ===== ANTIHYPERTENSIVE COMBINATIONS =====
  { genericName: "Amlodipine/Valsartan", brandNames: ["Exforge"], atcCode: "C09DB01", doseStrengths: ["5/80mg","5/160mg","10/160mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Once daily"], indication: "Hypertension (dual therapy)", nigeriaAvailable: "WIDELY_AVAILABLE", esml: false, nigeriaWeighting: 60, isControlled: false },
  { genericName: "Amlodipine/Lisinopril", brandNames: ["Lisinoaml","Amlipin-L"], atcCode: "C09BB03", doseStrengths: ["5/5mg","5/10mg","10/10mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Once daily"], indication: "Hypertension (dual therapy)", nigeriaAvailable: "WIDELY_AVAILABLE", esml: false, nigeriaWeighting: 60, isControlled: false },
  { genericName: "Losartan/Hydrochlorothiazide", brandNames: ["Hyzaar","Lozide Plus"], atcCode: "C09DA01", doseStrengths: ["50/12.5mg","100/25mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Once daily"], indication: "Hypertension (dual therapy)", nigeriaAvailable: "WIDELY_AVAILABLE", esml: false, nigeriaWeighting: 60, isControlled: false },
  { genericName: "Lisinopril/Hydrochlorothiazide", brandNames: ["Zestoretic","Prinzide"], atcCode: "C09BA03", doseStrengths: ["10/12.5mg","20/12.5mg","20/25mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Once daily"], indication: "Hypertension (dual therapy)", nigeriaAvailable: "WIDELY_AVAILABLE", esml: false, nigeriaWeighting: 55, isControlled: false },
  { genericName: "Telmisartan", brandNames: ["Micardis","Telma"], atcCode: "C09CA07", doseStrengths: ["20mg","40mg","80mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Once daily"], indication: "Hypertension, cardiovascular risk reduction", nigeriaAvailable: "WIDELY_AVAILABLE", esml: false, nigeriaWeighting: 55, isControlled: false },
  { genericName: "Valsartan", brandNames: ["Diovan","Valtan"], atcCode: "C09CA03", doseStrengths: ["40mg","80mg","160mg","320mg"], forms: ["Tablet","Capsule"], routes: ["Oral"], frequencies: ["Once daily"], indication: "Hypertension, heart failure, post-MI", nigeriaAvailable: "WIDELY_AVAILABLE", esml: false, nigeriaWeighting: 55, isControlled: false },
  { genericName: "Bisoprolol", brandNames: ["Concor"], atcCode: "C07AB07", doseStrengths: ["1.25mg","2.5mg","5mg","10mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Once daily"], indication: "Hypertension, heart failure, angina", nigeriaAvailable: "WIDELY_AVAILABLE", esml: false, nigeriaWeighting: 60, isControlled: false },
  { genericName: "Carvedilol", brandNames: ["Dilatrend","Coreg"], atcCode: "C07AG02", doseStrengths: ["3.125mg","6.25mg","12.5mg","25mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Twice daily"], indication: "Heart failure, hypertension", nigeriaAvailable: "WIDELY_AVAILABLE", esml: false, nigeriaWeighting: 55, isControlled: false },
  { genericName: "Ramipril", brandNames: ["Tritace","Altace"], atcCode: "C09AA05", doseStrengths: ["1.25mg","2.5mg","5mg","10mg"], forms: ["Capsule","Tablet"], routes: ["Oral"], frequencies: ["Once daily"], indication: "Hypertension, heart failure, post-MI", nigeriaAvailable: "WIDELY_AVAILABLE", esml: false, nigeriaWeighting: 60, isControlled: false },
  { genericName: "Enalapril", brandNames: ["Vasotec","Renitec"], atcCode: "C09AA02", doseStrengths: ["2.5mg","5mg","10mg","20mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Once daily","Twice daily"], indication: "Hypertension, heart failure", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 70, isControlled: false },
  { genericName: "Isosorbide Dinitrate", brandNames: ["Isordil","Sorbitrate"], atcCode: "C01DA08", doseStrengths: ["5mg","10mg","20mg","40mg"], forms: ["Tablet"], routes: ["Oral","Sublingual"], frequencies: ["Two to three times daily"], indication: "Angina pectoris, heart failure", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 60, isControlled: false },
  { genericName: "Glyceryl Trinitrate (GTN)", brandNames: ["Nitrostat","Angised"], atcCode: "C01DA02", doseStrengths: ["0.3mg","0.4mg","0.5mg","5mg/ml"], forms: ["Sublingual tablet","Spray","Infusion"], routes: ["Sublingual","IV"], frequencies: ["As needed for angina"], indication: "Acute angina, ACS, heart failure", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 60, isControlled: false },
  { genericName: "Amiodarone", brandNames: ["Cordarone","Pacerone"], atcCode: "C01BD01", doseStrengths: ["100mg","200mg","150mg/3ml"], forms: ["Tablet","Injection"], routes: ["Oral","IV"], frequencies: ["Once daily (maintenance)"], indication: "Ventricular/supraventricular arrhythmia", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 55, isControlled: false },

  // ===== ADDITIONAL ENT & TOPICAL =====
  { genericName: "Ciprofloxacin Ear Drops", brandNames: ["Ciplox Ear","Ciloxan"], atcCode: "S02AA15", doseStrengths: ["0.3%"], forms: ["Ear drop"], routes: ["Topical (otic)"], frequencies: ["Twice daily"], indication: "Otitis externa, chronic suppurative otitis media", nigeriaAvailable: "WIDELY_AVAILABLE", esml: false, nigeriaWeighting: 55, isControlled: false },
  { genericName: "Ofloxacin Ear/Eye Drops", brandNames: ["Oflox","Tarivid"], atcCode: "S01AE01", doseStrengths: ["0.3%"], forms: ["Eye/Ear drop"], routes: ["Topical"], frequencies: ["Two to four times daily"], indication: "Bacterial conjunctivitis, otitis externa", nigeriaAvailable: "WIDELY_AVAILABLE", esml: false, nigeriaWeighting: 55, isControlled: false },
  { genericName: "Xylometazoline", brandNames: ["Otrivin","Olynth"], atcCode: "R01AA07", doseStrengths: ["0.05%","0.1%"], forms: ["Nasal spray","Nasal drops"], routes: ["Nasal"], frequencies: ["Two to three times daily (max 7 days)"], indication: "Nasal congestion", nigeriaAvailable: "WIDELY_AVAILABLE", esml: false, nigeriaWeighting: 55, isControlled: false },
  { genericName: "Beclomethasone Nasal Spray", brandNames: ["Beconase"], atcCode: "R01AD01", doseStrengths: ["50mcg/spray"], forms: ["Nasal spray"], routes: ["Nasal"], frequencies: ["Twice daily"], indication: "Allergic rhinitis", nigeriaAvailable: "WIDELY_AVAILABLE", esml: false, nigeriaWeighting: 50, isControlled: false },
  { genericName: "Gentamicin Eye Drops", brandNames: ["Genticyn","Garamycin"], atcCode: "S01AA11", doseStrengths: ["0.3%"], forms: ["Eye drop"], routes: ["Topical (ophthalmic)"], frequencies: ["Every 4-6 hours"], indication: "Bacterial conjunctivitis, corneal ulcer", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 65, isControlled: false },
  { genericName: "Prednisolone Eye Drops", brandNames: ["Pred Forte","Minims Prednisolone"], atcCode: "S01BA04", doseStrengths: ["0.5%","1%"], forms: ["Eye drop"], routes: ["Topical (ophthalmic)"], frequencies: ["Two to four times daily"], indication: "Ocular inflammation, post-operative", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 55, isControlled: false },
  { genericName: "Tropicamide Eye Drops", brandNames: ["Mydriacyl"], atcCode: "S01FA06", doseStrengths: ["0.5%","1%"], forms: ["Eye drop"], routes: ["Topical (ophthalmic)"], frequencies: ["As needed"], indication: "Mydriasis for fundoscopy", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 50, isControlled: false },
  { genericName: "Fluorescein Eye Drops", brandNames: ["Fluorescein"], atcCode: "S01JA01", doseStrengths: ["1%","2%"], forms: ["Eye drop"], routes: ["Topical (ophthalmic)"], frequencies: ["As needed"], indication: "Corneal abrasion/ulcer detection", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 45, isControlled: false },
  { genericName: "Artificial Tears (CMC/Hypromellose)", brandNames: ["Tears Naturale","Celluvisc"], atcCode: "S01XA20", doseStrengths: ["0.5%","1%"], forms: ["Eye drop"], routes: ["Topical (ophthalmic)"], frequencies: ["As needed"], indication: "Dry eye syndrome", nigeriaAvailable: "WIDELY_AVAILABLE", esml: false, nigeriaWeighting: 50, isControlled: false },
  { genericName: "Mupirocin", brandNames: ["Bactroban"], atcCode: "D06AX09", doseStrengths: ["2%"], forms: ["Ointment","Cream"], routes: ["Topical"], frequencies: ["Three times daily"], indication: "Impetigo, wound infection, MRSA decolonisation", nigeriaAvailable: "WIDELY_AVAILABLE", esml: false, nigeriaWeighting: 50, isControlled: false },
  { genericName: "Fusidic Acid", brandNames: ["Fucidin"], atcCode: "D06AX01", doseStrengths: ["2%","250mg"], forms: ["Cream","Ointment","Tablet"], routes: ["Topical","Oral"], frequencies: ["Three times daily"], indication: "Staphylococcal skin infections", nigeriaAvailable: "WIDELY_AVAILABLE", esml: false, nigeriaWeighting: 55, isControlled: false },

  // ===== ADDITIONAL PAEDIATRIC =====
  { genericName: "Paracetamol Paediatric Drops", brandNames: ["Calpol","Panadol Baby Drops"], atcCode: "N02BE01", doseStrengths: ["100mg/ml","120mg/5ml"], forms: ["Oral drops","Suspension"], routes: ["Oral"], frequencies: ["Every 4-6 hours"], indication: "Paediatric pain and fever", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 95, isControlled: false },
  { genericName: "Ibuprofen Paediatric Suspension", brandNames: ["Brufen Syrup","Nurofen for Children"], atcCode: "M01AE01", doseStrengths: ["100mg/5ml"], forms: ["Suspension"], routes: ["Oral"], frequencies: ["Three times daily"], indication: "Paediatric pain, fever, inflammation", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 85, isControlled: false },
  { genericName: "Amoxicillin Paediatric Suspension", brandNames: ["Amoxil Syrup"], atcCode: "J01CA04", doseStrengths: ["125mg/5ml","250mg/5ml"], forms: ["Suspension"], routes: ["Oral"], frequencies: ["Three times daily"], indication: "Paediatric bacterial infections", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 95, isControlled: false },
  { genericName: "Salbutamol Syrup (Paediatric)", brandNames: ["Ventolin Syrup"], atcCode: "R03AC02", doseStrengths: ["2mg/5ml"], forms: ["Syrup"], routes: ["Oral"], frequencies: ["Three times daily"], indication: "Paediatric asthma, wheeze", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 80, isControlled: false },
  { genericName: "Multivitamin Drops (Paediatric)", brandNames: ["Abidec","Dagravit"], atcCode: "A11BA", doseStrengths: ["Various"], forms: ["Oral drops"], routes: ["Oral"], frequencies: ["Once daily"], indication: "Vitamin supplementation in infants/children", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 70, isControlled: false },
  { genericName: "Domperidone", brandNames: ["Motilium"], atcCode: "A03FA03", doseStrengths: ["10mg","1mg/ml"], forms: ["Tablet","Suspension"], routes: ["Oral"], frequencies: ["Three times daily"], indication: "Nausea, vomiting, gastroparesis", nigeriaAvailable: "WIDELY_AVAILABLE", esml: false, nigeriaWeighting: 65, isControlled: false },
  { genericName: "Gripe Water", brandNames: ["Woodward's","Bonnisan"], atcCode: "A03AX", doseStrengths: ["Various"], forms: ["Liquid"], routes: ["Oral"], frequencies: ["As needed"], indication: "Infant colic, gripe", nigeriaAvailable: "WIDELY_AVAILABLE", esml: false, nigeriaWeighting: 60, isControlled: false },

  // ===== ADDITIONAL ANTIBIOTICS =====
  { genericName: "Cefpodoxime", brandNames: ["Orelox","Vantin"], atcCode: "J01DD13", doseStrengths: ["100mg","200mg","40mg/5ml"], forms: ["Tablet","Suspension"], routes: ["Oral"], frequencies: ["Twice daily"], indication: "Respiratory, urinary infections", nigeriaAvailable: "WIDELY_AVAILABLE", esml: false, nigeriaWeighting: 55, isControlled: false },
  { genericName: "Ceftazidime", brandNames: ["Fortum","Fortaz"], atcCode: "J01DD02", doseStrengths: ["250mg","500mg","1g","2g"], forms: ["Injection"], routes: ["IV","IM"], frequencies: ["Three times daily"], indication: "Pseudomonas, severe gram-negative infections", nigeriaAvailable: "LIMITED", esml: true, nigeriaWeighting: 50, isControlled: false },
  { genericName: "Imipenem/Cilastatin", brandNames: ["Tienam"], atcCode: "J01DH51", doseStrengths: ["500mg/500mg"], forms: ["Injection"], routes: ["IV"], frequencies: ["Every 6-8 hours"], indication: "Severe multi-drug resistant infections", nigeriaAvailable: "LIMITED", esml: true, nigeriaWeighting: 45, isControlled: false },
  { genericName: "Piperacillin/Tazobactam", brandNames: ["Tazocin","Zosyn"], atcCode: "J01CR05", doseStrengths: ["2g/250mg","4g/500mg"], forms: ["Injection"], routes: ["IV"], frequencies: ["Every 6-8 hours"], indication: "Nosocomial infections, complicated intra-abdominal", nigeriaAvailable: "LIMITED", esml: false, nigeriaWeighting: 45, isControlled: false },
  { genericName: "Linezolid", brandNames: ["Zyvox"], atcCode: "J01XX08", doseStrengths: ["600mg","2mg/ml"], forms: ["Tablet","Infusion"], routes: ["Oral","IV"], frequencies: ["Twice daily"], indication: "MRSA, VRE, MDR-TB", nigeriaAvailable: "LIMITED", esml: false, nigeriaWeighting: 35, isControlled: false },
  { genericName: "Colistimethate (Colistin)", brandNames: ["Colomycin","Colistin"], atcCode: "J01XB01", doseStrengths: ["1MIU","2MIU"], forms: ["Injection"], routes: ["IV","Nebulised"], frequencies: ["Two to three times daily"], indication: "MDR gram-negative infections (last resort)", nigeriaAvailable: "LIMITED", esml: false, nigeriaWeighting: 30, isControlled: false },
  { genericName: "Fosfomycin", brandNames: ["Monurol","Fosfocin"], atcCode: "J01XX01", doseStrengths: ["3g"], forms: ["Sachet"], routes: ["Oral"], frequencies: ["Single dose"], indication: "Uncomplicated UTI", nigeriaAvailable: "LIMITED", esml: false, nigeriaWeighting: 35, isControlled: false },

  // ===== ADDITIONAL ANTIVIRALS =====
  { genericName: "Acyclovir", brandNames: ["Zovirax","Acivir"], atcCode: "J05AB01", doseStrengths: ["200mg","400mg","800mg","250mg","3%","5%"], forms: ["Tablet","Injection","Eye ointment","Cream"], routes: ["Oral","IV","Topical"], frequencies: ["Five times daily (oral)","Every 8 hours (IV)"], indication: "HSV, VZV, herpes encephalitis", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 70, isControlled: false },
  { genericName: "Valacyclovir", brandNames: ["Valtrex"], atcCode: "J05AB11", doseStrengths: ["500mg","1000mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Twice daily","Three times daily"], indication: "HSV, VZV (better bioavailability)", nigeriaAvailable: "WIDELY_AVAILABLE", esml: false, nigeriaWeighting: 50, isControlled: false },
  { genericName: "Oseltamivir", brandNames: ["Tamiflu"], atcCode: "J05AH02", doseStrengths: ["30mg","45mg","75mg"], forms: ["Capsule","Suspension"], routes: ["Oral"], frequencies: ["Twice daily x 5 days"], indication: "Influenza A/B (treatment and prophylaxis)", nigeriaAvailable: "LIMITED", esml: false, nigeriaWeighting: 35, isControlled: false },

  // ===== ADDITIONAL RESPIRATORY =====
  { genericName: "Montelukast", brandNames: ["Singulair","Montair"], atcCode: "R03DC03", doseStrengths: ["4mg","5mg","10mg"], forms: ["Tablet","Chewable"], routes: ["Oral"], frequencies: ["Once daily at bedtime"], indication: "Asthma (add-on), allergic rhinitis", nigeriaAvailable: "WIDELY_AVAILABLE", esml: false, nigeriaWeighting: 55, isControlled: false },
  { genericName: "Tiotropium", brandNames: ["Spiriva"], atcCode: "R03BB04", doseStrengths: ["18mcg","2.5mcg"], forms: ["DPI","Soft mist inhaler"], routes: ["Inhaled"], frequencies: ["Once daily"], indication: "COPD maintenance", nigeriaAvailable: "LIMITED", esml: false, nigeriaWeighting: 40, isControlled: false },
  { genericName: "Formoterol/Budesonide", brandNames: ["Symbicort"], atcCode: "R03AK07", doseStrengths: ["6/100mcg","6/200mcg","6/400mcg"], forms: ["DPI","MDI"], routes: ["Inhaled"], frequencies: ["Twice daily"], indication: "Asthma, COPD", nigeriaAvailable: "LIMITED", esml: false, nigeriaWeighting: 45, isControlled: false },
  { genericName: "Bromhexine", brandNames: ["Bisolvon"], atcCode: "R05CB02", doseStrengths: ["4mg/5ml","8mg"], forms: ["Syrup","Tablet"], routes: ["Oral"], frequencies: ["Three times daily"], indication: "Mucolytic, productive cough", nigeriaAvailable: "WIDELY_AVAILABLE", esml: false, nigeriaWeighting: 60, isControlled: false },
  { genericName: "Guaifenesin", brandNames: ["Benylin Expectorant","Robitussin"], atcCode: "R05CA03", doseStrengths: ["100mg/5ml","200mg"], forms: ["Syrup","Tablet"], routes: ["Oral"], frequencies: ["Three to four times daily"], indication: "Expectorant, productive cough", nigeriaAvailable: "WIDELY_AVAILABLE", esml: false, nigeriaWeighting: 60, isControlled: false },
  { genericName: "Dextromethorphan", brandNames: ["Benylin DM","Robitussin DM"], atcCode: "R05DA09", doseStrengths: ["10mg/5ml","15mg"], forms: ["Syrup","Capsule"], routes: ["Oral"], frequencies: ["Every 4-6 hours"], indication: "Dry/non-productive cough", nigeriaAvailable: "WIDELY_AVAILABLE", esml: false, nigeriaWeighting: 55, isControlled: false },

  // ===== ADDITIONAL GI =====
  { genericName: "Pantoprazole", brandNames: ["Pantoloc","Protonix"], atcCode: "A02BC02", doseStrengths: ["20mg","40mg"], forms: ["Tablet","Injection"], routes: ["Oral","IV"], frequencies: ["Once daily"], indication: "GORD, peptic ulcer, stress ulcer prophylaxis", nigeriaAvailable: "WIDELY_AVAILABLE", esml: false, nigeriaWeighting: 65, isControlled: false },
  { genericName: "Lansoprazole", brandNames: ["Prevacid","Zoton"], atcCode: "A02BC03", doseStrengths: ["15mg","30mg"], forms: ["Capsule"], routes: ["Oral"], frequencies: ["Once daily"], indication: "GORD, peptic ulcer", nigeriaAvailable: "WIDELY_AVAILABLE", esml: false, nigeriaWeighting: 55, isControlled: false },
  { genericName: "Lactulose", brandNames: ["Duphalac","Laevolac"], atcCode: "A06AD11", doseStrengths: ["3.35g/5ml"], forms: ["Syrup"], routes: ["Oral"], frequencies: ["Once to twice daily"], indication: "Constipation, hepatic encephalopathy", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 60, isControlled: false },
  { genericName: "Bisacodyl", brandNames: ["Dulcolax"], atcCode: "A06AB02", doseStrengths: ["5mg","10mg"], forms: ["Tablet","Suppository"], routes: ["Oral","Rectal"], frequencies: ["Once daily"], indication: "Constipation, bowel preparation", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 55, isControlled: false },
  { genericName: "Mesalazine (5-ASA)", brandNames: ["Asacol","Pentasa","Salofalk"], atcCode: "A07EC02", doseStrengths: ["250mg","400mg","500mg","1g"], forms: ["Tablet","Suppository","Enema"], routes: ["Oral","Rectal"], frequencies: ["Two to three times daily"], indication: "Ulcerative colitis, Crohn's disease", nigeriaAvailable: "LIMITED", esml: false, nigeriaWeighting: 35, isControlled: false },

  // ===== ADDITIONAL PSYCHIATRIC / NEURO =====
  { genericName: "Gabapentin", brandNames: ["Neurontin","Gabin"], atcCode: "N03AX12", doseStrengths: ["100mg","300mg","400mg","600mg","800mg"], forms: ["Capsule","Tablet"], routes: ["Oral"], frequencies: ["Three times daily"], indication: "Neuropathic pain, epilepsy, anxiety", nigeriaAvailable: "WIDELY_AVAILABLE", esml: false, nigeriaWeighting: 55, isControlled: false },
  { genericName: "Pregabalin", brandNames: ["Lyrica","Pregabalin"], atcCode: "N03AX16", doseStrengths: ["25mg","50mg","75mg","150mg","300mg"], forms: ["Capsule"], routes: ["Oral"], frequencies: ["Twice daily"], indication: "Neuropathic pain, generalised anxiety, fibromyalgia", nigeriaAvailable: "WIDELY_AVAILABLE", esml: false, nigeriaWeighting: 50, isControlled: true, notes: "Schedule 4 controlled substance in some jurisdictions" },
  { genericName: "Escitalopram", brandNames: ["Lexapro","Cipralex"], atcCode: "N06AB10", doseStrengths: ["5mg","10mg","20mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Once daily"], indication: "Depression, generalised anxiety", nigeriaAvailable: "LIMITED", esml: false, nigeriaWeighting: 40, isControlled: false },
  { genericName: "Mirtazapine", brandNames: ["Remeron"], atcCode: "N06AX11", doseStrengths: ["15mg","30mg","45mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Once daily at bedtime"], indication: "Depression (with insomnia/poor appetite)", nigeriaAvailable: "LIMITED", esml: false, nigeriaWeighting: 35, isControlled: false },
  { genericName: "Lithium Carbonate", brandNames: ["Priadel","Camcolit"], atcCode: "N05AN01", doseStrengths: ["200mg","300mg","400mg"], forms: ["Tablet","Capsule"], routes: ["Oral"], frequencies: ["Twice daily"], indication: "Bipolar disorder (mood stabiliser)", nigeriaAvailable: "LIMITED", esml: true, nigeriaWeighting: 40, isControlled: false },
  { genericName: "Clonazepam", brandNames: ["Rivotril","Klonopin"], atcCode: "N03AE01", doseStrengths: ["0.5mg","1mg","2mg"], forms: ["Tablet","Injection"], routes: ["Oral","IV"], frequencies: ["Twice daily"], indication: "Epilepsy, panic disorder, myoclonus", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 50, isControlled: true, notes: "Schedule 4 controlled substance" },
  { genericName: "Benzhexol (Trihexyphenidyl)", brandNames: ["Artane","Benzhexol"], atcCode: "N04AA01", doseStrengths: ["2mg","5mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Three times daily"], indication: "Drug-induced extrapyramidal symptoms, parkinsonism", nigeriaAvailable: "WIDELY_AVAILABLE", esml: true, nigeriaWeighting: 55, isControlled: false },
  { genericName: "Levodopa/Carbidopa", brandNames: ["Sinemet","Madopar"], atcCode: "N04BA02", doseStrengths: ["100/25mg","250/25mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Three times daily"], indication: "Parkinson's disease", nigeriaAvailable: "LIMITED", esml: true, nigeriaWeighting: 45, isControlled: false },

  // ===== IMMUNOSUPPRESSANTS =====
  { genericName: "Azathioprine", brandNames: ["Imuran"], atcCode: "L04AX01", doseStrengths: ["25mg","50mg"], forms: ["Tablet"], routes: ["Oral"], frequencies: ["Once daily","Twice daily"], indication: "Organ transplant rejection, autoimmune diseases", nigeriaAvailable: "LIMITED", esml: true, nigeriaWeighting: 45, isControlled: false },
  { genericName: "Mycophenolate Mofetil", brandNames: ["CellCept","Myfortic"], atcCode: "L04AA06", doseStrengths: ["250mg","500mg"], forms: ["Capsule","Tablet"], routes: ["Oral"], frequencies: ["Twice daily"], indication: "Transplant rejection, lupus nephritis", nigeriaAvailable: "LIMITED", esml: false, nigeriaWeighting: 35, isControlled: false },
  { genericName: "Ciclosporin (Cyclosporine)", brandNames: ["Sandimmun","Neoral"], atcCode: "L04AD01", doseStrengths: ["25mg","50mg","100mg"], forms: ["Capsule","Oral solution"], routes: ["Oral"], frequencies: ["Twice daily"], indication: "Organ transplant rejection, psoriasis, nephrotic syndrome", nigeriaAvailable: "LIMITED", esml: true, nigeriaWeighting: 40, isControlled: false },

  // ===== BLOOD PRODUCTS & HAEMATINICS =====
  { genericName: "Iron Dextran/Sucrose (IV Iron)", brandNames: ["Cosmofer","Venofer"], atcCode: "B03AC", doseStrengths: ["50mg/ml","20mg/ml"], forms: ["Injection"], routes: ["IV"], frequencies: ["As directed"], indication: "Iron-deficiency anaemia (oral intolerance/severe)", nigeriaAvailable: "LIMITED", esml: true, nigeriaWeighting: 55, isControlled: false },
  { genericName: "Erythropoietin (EPO)", brandNames: ["Eprex","NeoRecormon"], atcCode: "B03XA01", doseStrengths: ["2000IU","4000IU","10000IU"], forms: ["Injection"], routes: ["SC","IV"], frequencies: ["One to three times weekly"], indication: "Anaemia in CKD, chemotherapy-induced anaemia", nigeriaAvailable: "LIMITED", esml: false, nigeriaWeighting: 40, isControlled: false },
  { genericName: "Anti-D Immunoglobulin", brandNames: ["RhoGAM","Rhophylac"], atcCode: "J06BB01", doseStrengths: ["300mcg","1500IU"], forms: ["Injection"], routes: ["IM","IV"], frequencies: ["Single dose per event"], indication: "Rh-D negative mother (prevent haemolytic disease)", nigeriaAvailable: "LIMITED", esml: true, nigeriaWeighting: 55, isControlled: false },
  { genericName: "Human Normal Immunoglobulin (IVIG)", brandNames: ["Octagam","Privigen"], atcCode: "J06BA02", doseStrengths: ["5%","10%"], forms: ["Infusion"], routes: ["IV"], frequencies: ["As per protocol"], indication: "Immunodeficiency, ITP, Guillain-Barré, Kawasaki", nigeriaAvailable: "RARELY_AVAILABLE", esml: false, nigeriaWeighting: 30, isControlled: false },
];

const prisma = new PrismaClient();

async function main() {
  console.log("Seeding FormularyDrug table...");

  let created = 0;
  let skipped = 0;

  for (const drug of drugs) {
    const existing = await prisma.formularyDrug.findFirst({
      where: { genericName: drug.genericName },
    });

    if (existing) {
      skipped++;
      continue;
    }

    await prisma.formularyDrug.create({
      data: {
        genericName: drug.genericName,
        brandNames: drug.brandNames,
        atcCode: drug.atcCode || null,
        doseStrengths: drug.doseStrengths,
        forms: drug.forms,
        routes: drug.routes,
        frequencies: drug.frequencies,
        indication: drug.indication || null,
        nigeriaAvailable: drug.nigeriaAvailable,
        esml: drug.esml,
        nigeriaWeighting: drug.nigeriaWeighting,
        isControlled: drug.isControlled,
        notes: (drug as Record<string, unknown>).notes as string || null,
      },
    });
    created++;
  }

  console.log(`Done. Created: ${created}, Skipped (already exist): ${skipped}`);
  console.log(`Total drugs in seed: ${drugs.length}`);
}

main()
  .catch((e) => {
    console.error("Seed error:", e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
