import 'server-only';

import { callClaude } from './service';

// ============================================
// CONSTANTS
// ============================================

export const CDSS_DISCLAIMER =
  'CLINICAL DECISION SUPPORT NOTICE: This information is generated by an AI system and is intended to assist — not replace — clinical judgement. All suggestions must be independently verified by the treating physician. The Doctors Foundation for Care (DFC) accepts no liability for clinical decisions made based on AI-generated content.';

export const NIGERIA_CONTEXT = `Nigerian Epidemiological Context:
- Malaria: hyperendemic (Plasmodium falciparum dominant), always consider in febrile illness
- Sickle Cell Disease: highest global prevalence (HbSS ~2-3% of births), screen before sulphonamides/oxidant drugs
- Tuberculosis: incidence ~219/100,000; consider in chronic cough, weight loss, night sweats
- HIV: ~1.4 million on ART; always check ART drug interactions
- Typhoid/enteric fever: endemic; consider in prolonged fever with relative bradycardia
- Lassa fever: seasonal (Dec-Mar), consider in febrile illness with pharyngitis/retrosternal pain
- Artemether-lumefantrine (Coartem): first-line antimalarial — interacts with CYP3A4 substrates, QT-prolonging drugs, and many antiretrovirals
- Formulary considerations: not all Western medications are readily available; consider NAFDAC-approved alternatives
- Common comorbidities: hypertension, diabetes (often undiagnosed), chronic kidney disease`;

// ============================================
// TYPES
// ============================================

export interface DrugAllergyResult {
  hasInteraction: boolean;
  level: 'CRITICAL' | 'WARNING' | 'INFO';
  title: string;
  explanation: string;
  suggestion: string;
}

export interface DrugInteraction {
  severity: 'CRITICAL' | 'MODERATE' | 'MINOR';
  withDrug: string;
  mechanism: string;
  clinicalEffect: string;
  recommendation: string;
}

export interface Differential {
  diagnosis: string;
  probability: 'HIGH' | 'MODERATE' | 'LOW';
  supportingFeatures: string[];
  keyInvestigations: string[];
}

export interface DifferentialResult {
  differentials: Differential[];
  redFlags: string[];
  disclaimer: string;
}

export interface GuidelineReminder {
  category: string;
  reminder: string;
  priority: 'HIGH' | 'NORMAL' | 'LOW';
}

export interface LabInterpretation {
  summary: string;
  criticalFindings: string[];
  possibleCauses: string[];
  recommendedActions: string[];
  urgency: 'CRITICAL' | 'URGENT' | 'ROUTINE';
  disclaimer: string;
}

export interface RiskScore {
  scoreName: string;
  score: number;
  interpretation: string;
  recommendation: string;
  level: 'CRITICAL' | 'WARNING' | 'INFO';
}

export interface SOAPReviewResult {
  isComplete: boolean;
  gaps: string[];
  warnings: string[];
  suggestions: string[];
}

export interface FormularyResult {
  availabilityStatus: 'AVAILABLE' | 'LIMITED' | 'UNAVAILABLE' | 'UNKNOWN';
  notes: string;
  alternatives: string[];
}

// ============================================
// AI FUNCTIONS
// ============================================

function parseJSON<T>(raw: string, fallback: T): T {
  try {
    return JSON.parse(raw.replace(/```json|```/g, '').trim()) as T;
  } catch {
    return fallback;
  }
}

/**
 * Checks a new drug against patient allergies for contraindications/cross-reactivity.
 */
export async function checkDrugAllergy(
  newDrug: string,
  newDrugClass: string | undefined,
  allergies: Array<{ allergen: string; allergyType: string; reaction: string; severity: string }>,
): Promise<DrugAllergyResult> {
  const fallback: DrugAllergyResult = {
    hasInteraction: false,
    level: 'INFO',
    title: 'Unable to assess drug-allergy interaction',
    explanation: 'The system could not complete the allergy check. Please verify manually.',
    suggestion: 'Review patient allergy list before prescribing.',
  };

  if (!allergies.length) {
    return {
      hasInteraction: false,
      level: 'INFO',
      title: 'No known allergies on record',
      explanation: 'Patient has no documented allergies.',
      suggestion: 'Confirm allergy history with patient before prescribing.',
    };
  }

  try {
    const system = `You are a clinical pharmacology decision support system. Assess drug-allergy interactions and cross-reactivity. ${NIGERIA_CONTEXT}

Respond ONLY with valid JSON, no markdown wrapping. Use this exact schema:
{
  "hasInteraction": boolean,
  "level": "CRITICAL" | "WARNING" | "INFO",
  "title": "short title",
  "explanation": "clinical explanation",
  "suggestion": "what the physician should do"
}

Rules:
- CRITICAL: known allergy to this drug or high cross-reactivity (e.g., penicillin allergy + amoxicillin)
- WARNING: moderate cross-reactivity or same drug class with uncertain cross-reactivity
- INFO: low cross-reactivity risk but worth noting`;

    const prompt = `New drug to prescribe: ${newDrug}${newDrugClass ? ` (class: ${newDrugClass})` : ''}

Patient allergies:
${allergies.map((a, i) => `${i + 1}. Allergen: ${a.allergen} | Type: ${a.allergyType} | Reaction: ${a.reaction} | Severity: ${a.severity}`).join('\n')}

Assess the interaction risk.`;

    const raw = await callClaude(system, prompt, 500);
    return parseJSON(raw, fallback);
  } catch {
    return fallback;
  }
}

/**
 * Checks a new drug against current medications for interactions.
 */
export async function checkDrugInteractions(
  newDrug: string,
  currentMedications: Array<{ drugName: string; dose: string; frequency: string }>,
  patientAge?: number,
): Promise<DrugInteraction[]> {
  const fallback: DrugInteraction[] = [];

  if (!currentMedications.length) {
    return fallback;
  }

  try {
    const system = `You are a clinical pharmacology decision support system specialising in drug-drug interactions. ${NIGERIA_CONTEXT}

Respond ONLY with valid JSON array, no markdown wrapping. Each element:
{
  "severity": "CRITICAL" | "MODERATE" | "MINOR",
  "withDrug": "name of the interacting current medication",
  "mechanism": "pharmacological mechanism",
  "clinicalEffect": "what may happen clinically",
  "recommendation": "action for physician"
}

Return an empty array [] if no interactions found.

Key interactions to always check:
- QT prolongation combinations
- CYP450 inhibitors/inducers (especially CYP3A4 with artemether-lumefantrine)
- Serotonin syndrome combinations
- Nephrotoxic combinations
- Anticoagulant potentiation
- ART drug interactions (if on HIV treatment)`;

    const prompt = `New drug to prescribe: ${newDrug}
${patientAge ? `Patient age: ${patientAge} years` : ''}

Current medications:
${currentMedications.map((m, i) => `${i + 1}. ${m.drugName} ${m.dose} ${m.frequency}`).join('\n')}

Identify all clinically significant drug-drug interactions.`;

    const raw = await callClaude(system, prompt, 1200);
    const parsed = parseJSON<DrugInteraction[]>(raw, fallback);
    return Array.isArray(parsed) ? parsed : fallback;
  } catch {
    return fallback;
  }
}

/**
 * Generates differential diagnoses from clinical picture for physician consideration.
 */
export async function generateDifferentials(
  chiefComplaint: string,
  symptoms: string[],
  patientContext: {
    age?: number;
    gender?: string;
    problems?: string[];
    medications?: string[];
    vitals?: Record<string, string | number>;
  },
): Promise<DifferentialResult> {
  const fallback: DifferentialResult = {
    differentials: [],
    redFlags: [],
    disclaimer: CDSS_DISCLAIMER,
  };

  try {
    const system = `You are a clinical decision support system assisting physicians with differential diagnosis generation. ${NIGERIA_CONTEXT}

IMPORTANT: You are NOT diagnosing the patient. You are generating a list of differentials for the physician to consider. The physician makes all diagnostic decisions.

Respond ONLY with valid JSON, no markdown wrapping:
{
  "differentials": [
    {
      "diagnosis": "name",
      "probability": "HIGH" | "MODERATE" | "LOW",
      "supportingFeatures": ["feature1", "feature2"],
      "keyInvestigations": ["investigation1", "investigation2"]
    }
  ],
  "redFlags": ["any red flags requiring immediate attention"]
}

Always consider tropical/endemic diseases relevant to Nigeria alongside standard differentials. Return 3-7 differentials ordered by probability.`;

    const prompt = `Chief complaint: ${chiefComplaint}
Symptoms: ${symptoms.join(', ')}
${patientContext.age ? `Age: ${patientContext.age} years` : ''}
${patientContext.gender ? `Gender: ${patientContext.gender}` : ''}
${patientContext.problems?.length ? `Active problems: ${patientContext.problems.join(', ')}` : ''}
${patientContext.medications?.length ? `Current medications: ${patientContext.medications.join(', ')}` : ''}
${patientContext.vitals ? `Vitals: ${JSON.stringify(patientContext.vitals)}` : ''}

Generate differential diagnoses for physician consideration.`;

    const raw = await callClaude(system, prompt, 1500);
    const parsed = parseJSON<Omit<DifferentialResult, 'disclaimer'>>(raw, { differentials: [], redFlags: [] });
    return {
      differentials: Array.isArray(parsed.differentials) ? parsed.differentials : [],
      redFlags: Array.isArray(parsed.redFlags) ? parsed.redFlags : [],
      disclaimer: CDSS_DISCLAIMER,
    };
  } catch {
    return fallback;
  }
}

/**
 * Returns contextual clinical guideline prompts based on diagnosis.
 */
export async function getGuidelineReminders(
  diagnosis: string,
  patientContext: {
    age?: number;
    gender?: string;
    problems?: string[];
    medications?: string[];
  },
): Promise<GuidelineReminder[]> {
  const fallback: GuidelineReminder[] = [];

  try {
    const system = `You are a clinical guidelines decision support system. Provide contextual reminders based on current Nigerian and international clinical guidelines (WHO, NICE, AHA/ACC, FMOH Nigeria).

${NIGERIA_CONTEXT}

Respond ONLY with valid JSON array, no markdown wrapping. Each element:
{
  "category": "SCREENING" | "INVESTIGATION" | "MEDICATION" | "MONITORING" | "REFERRAL" | "LIFESTYLE" | "FOLLOW_UP",
  "reminder": "the guideline reminder text",
  "priority": "HIGH" | "NORMAL" | "LOW"
}

Focus on:
- Mandatory investigations for the diagnosis
- Drug monitoring requirements
- Screening recommendations given age/gender/comorbidities
- Follow-up scheduling
- Vaccination/prophylaxis reminders
- Nigerian-specific protocols (FMOH, NMEP for malaria, NASCP for HIV)`;

    const prompt = `Diagnosis: ${diagnosis}
${patientContext.age ? `Age: ${patientContext.age} years` : ''}
${patientContext.gender ? `Gender: ${patientContext.gender}` : ''}
${patientContext.problems?.length ? `Comorbidities: ${patientContext.problems.join(', ')}` : ''}
${patientContext.medications?.length ? `Current medications: ${patientContext.medications.join(', ')}` : ''}

Provide relevant clinical guideline reminders.`;

    const raw = await callClaude(system, prompt, 1200);
    const parsed = parseJSON<GuidelineReminder[]>(raw, fallback);
    return Array.isArray(parsed) ? parsed : fallback;
  } catch {
    return fallback;
  }
}

/**
 * Interprets abnormal lab results in clinical context.
 */
export async function interpretAbnormalLab(
  labResult: {
    testName: string;
    results: Array<{ test: string; value: string; unit: string; refRange: string; flag: string }>;
    labName?: string;
    reportDate: string;
  },
  patientContext: {
    age?: number;
    gender?: string;
    problems?: string[];
    medications?: string[];
  },
): Promise<LabInterpretation> {
  const fallback: LabInterpretation = {
    summary: 'Unable to interpret lab results automatically. Please review manually.',
    criticalFindings: [],
    possibleCauses: [],
    recommendedActions: ['Review lab results manually'],
    urgency: 'ROUTINE',
    disclaimer: CDSS_DISCLAIMER,
  };

  try {
    const system = `You are a clinical laboratory interpretation decision support system. Interpret abnormal lab results in clinical context. ${NIGERIA_CONTEXT}

IMPORTANT: You are providing interpretive support — the physician makes all clinical decisions.

Respond ONLY with valid JSON, no markdown wrapping:
{
  "summary": "brief overall interpretation",
  "criticalFindings": ["any critically abnormal values requiring immediate action"],
  "possibleCauses": ["possible aetiologies for the abnormal results"],
  "recommendedActions": ["suggested next steps"],
  "urgency": "CRITICAL" | "URGENT" | "ROUTINE"
}

CRITICAL: values incompatible with life or requiring immediate intervention
URGENT: significantly abnormal, needs attention within hours
ROUTINE: mildly abnormal, routine follow-up`;

    const prompt = `Lab: ${labResult.testName}${labResult.labName ? ` (${labResult.labName})` : ''}
Report date: ${labResult.reportDate}

Results:
${labResult.results.map((r) => `- ${r.test}: ${r.value} ${r.unit} (ref: ${r.refRange}) [${r.flag}]`).join('\n')}

${patientContext.age ? `Patient age: ${patientContext.age} years` : ''}
${patientContext.gender ? `Gender: ${patientContext.gender}` : ''}
${patientContext.problems?.length ? `Active problems: ${patientContext.problems.join(', ')}` : ''}
${patientContext.medications?.length ? `Medications: ${patientContext.medications.join(', ')}` : ''}

Interpret these abnormal results.`;

    const raw = await callClaude(system, prompt, 1000);
    const parsed = parseJSON<Omit<LabInterpretation, 'disclaimer'>>(raw, {
      summary: fallback.summary,
      criticalFindings: [],
      possibleCauses: [],
      recommendedActions: fallback.recommendedActions,
      urgency: 'ROUTINE' as const,
    });
    return { ...parsed, disclaimer: CDSS_DISCLAIMER };
  } catch {
    return fallback;
  }
}

/**
 * DETERMINISTIC — no AI call. Calculates qSOFA, BP alerts, SpO2 alerts from vitals.
 */
export function calculateRiskScores(
  vitals: {
    systolicBP?: number | null;
    diastolicBP?: number | null;
    heartRate?: number | null;
    respiratoryRate?: number | null;
    temperature?: number | null;
    oxygenSat?: number | null;
    bloodGlucose?: number | null;
  },
  gcsScore?: number,
): RiskScore[] {
  const scores: RiskScore[] = [];

  // --- qSOFA (Quick Sequential Organ Failure Assessment) ---
  let qsofa = 0;
  if (vitals.systolicBP != null && vitals.systolicBP <= 100) qsofa++;
  if (vitals.respiratoryRate != null && vitals.respiratoryRate >= 22) qsofa++;
  if (gcsScore != null && gcsScore < 15) qsofa++;

  if (vitals.systolicBP != null || vitals.respiratoryRate != null) {
    let interpretation: string;
    let level: RiskScore['level'];
    let recommendation: string;

    if (qsofa >= 2) {
      interpretation = 'High risk of poor outcome — meets sepsis screening criteria';
      level = 'CRITICAL';
      recommendation = 'Initiate sepsis workup: blood cultures, lactate, FBC, U&E, CRP. Consider early antibiotics and IV fluids per Surviving Sepsis Campaign guidelines.';
    } else if (qsofa === 1) {
      interpretation = 'Intermediate risk — one qSOFA criterion met';
      level = 'WARNING';
      recommendation = 'Monitor closely. Reassess within 1 hour. Consider full sepsis screening if clinical suspicion.';
    } else {
      interpretation = 'Low qSOFA score — sepsis less likely based on vitals alone';
      level = 'INFO';
      recommendation = 'Continue routine monitoring. qSOFA alone does not rule out infection.';
    }

    scores.push({ scoreName: 'qSOFA', score: qsofa, interpretation, recommendation, level });
  }

  // --- Blood Pressure Alert ---
  if (vitals.systolicBP != null && vitals.diastolicBP != null) {
    const sbp = vitals.systolicBP;
    const dbp = vitals.diastolicBP;

    if (sbp >= 180 || dbp >= 120) {
      scores.push({
        scoreName: 'Blood Pressure',
        score: sbp,
        interpretation: 'Hypertensive crisis (SBP >= 180 or DBP >= 120)',
        recommendation: 'Assess for target organ damage (headache, chest pain, visual changes, AKI). If present: hypertensive emergency — IV antihypertensives. If absent: hypertensive urgency — oral agents, recheck in 1-2 hours.',
        level: 'CRITICAL',
      });
    } else if (sbp >= 140 || dbp >= 90) {
      scores.push({
        scoreName: 'Blood Pressure',
        score: sbp,
        interpretation: `Hypertension (${sbp}/${dbp} mmHg)`,
        recommendation: 'Confirm with repeat measurement. If persistent, review antihypertensive regimen. Target <140/90 (or <130/80 if diabetic/CKD).',
        level: 'WARNING',
      });
    } else if (sbp < 90 || dbp < 60) {
      scores.push({
        scoreName: 'Blood Pressure',
        score: sbp,
        interpretation: `Hypotension (${sbp}/${dbp} mmHg)`,
        recommendation: 'Assess for shock (tachycardia, altered mentation, poor perfusion). Consider IV fluid bolus. Review medications that may cause hypotension.',
        level: 'CRITICAL',
      });
    }
  }

  // --- SpO2 Alert ---
  if (vitals.oxygenSat != null) {
    const spo2 = Number(vitals.oxygenSat);

    if (spo2 < 90) {
      scores.push({
        scoreName: 'Oxygen Saturation',
        score: spo2,
        interpretation: `Severe hypoxaemia (SpO2 ${spo2}%)`,
        recommendation: 'Immediate supplemental oxygen. Assess airway, breathing. Consider ABG. Investigate cause: pneumonia, PE, asthma exacerbation, pneumothorax.',
        level: 'CRITICAL',
      });
    } else if (spo2 < 94) {
      scores.push({
        scoreName: 'Oxygen Saturation',
        score: spo2,
        interpretation: `Hypoxaemia (SpO2 ${spo2}%)`,
        recommendation: 'Initiate supplemental oxygen to target SpO2 94-98% (88-92% if COPD). Investigate underlying cause.',
        level: 'WARNING',
      });
    }
  }

  // --- Heart Rate Alert ---
  if (vitals.heartRate != null) {
    const hr = vitals.heartRate;

    if (hr > 150) {
      scores.push({
        scoreName: 'Heart Rate',
        score: hr,
        interpretation: `Severe tachycardia (HR ${hr} bpm)`,
        recommendation: 'Obtain 12-lead ECG. Assess haemodynamic stability. Consider SVT, VT, or secondary tachycardia (sepsis, hypovolaemia, PE).',
        level: 'CRITICAL',
      });
    } else if (hr > 100) {
      scores.push({
        scoreName: 'Heart Rate',
        score: hr,
        interpretation: `Tachycardia (HR ${hr} bpm)`,
        recommendation: 'Investigate cause: pain, anxiety, fever, dehydration, anaemia, infection. Obtain ECG if new or sustained.',
        level: 'WARNING',
      });
    } else if (hr < 50) {
      scores.push({
        scoreName: 'Heart Rate',
        score: hr,
        interpretation: `Bradycardia (HR ${hr} bpm)`,
        recommendation: 'Assess for symptoms (dizziness, syncope). Review medications (beta-blockers, digoxin, CCBs). Obtain ECG to assess rhythm.',
        level: hr < 40 ? 'CRITICAL' : 'WARNING',
      });
    }
  }

  // --- Temperature Alert ---
  if (vitals.temperature != null) {
    const temp = Number(vitals.temperature);

    if (temp >= 40) {
      scores.push({
        scoreName: 'Temperature',
        score: temp,
        interpretation: `High fever (${temp}C)`,
        recommendation: 'Malaria RDT/film (in Nigeria, always rule out malaria first). Blood cultures. Consider antipyretics, tepid sponging. Investigate: infection, heat stroke, drug reaction.',
        level: 'CRITICAL',
      });
    } else if (temp >= 38) {
      scores.push({
        scoreName: 'Temperature',
        score: temp,
        interpretation: `Fever (${temp}C)`,
        recommendation: 'In endemic area: malaria RDT/film. Consider infection workup: FBC, blood culture, urinalysis. Antipyretics as needed.',
        level: 'WARNING',
      });
    } else if (temp < 35) {
      scores.push({
        scoreName: 'Temperature',
        score: temp,
        interpretation: `Hypothermia (${temp}C)`,
        recommendation: 'Active warming. Assess for sepsis (hypothermia can indicate severe sepsis), hypothyroidism, exposure. Check blood glucose.',
        level: 'CRITICAL',
      });
    }
  }

  // --- Blood Glucose Alert ---
  if (vitals.bloodGlucose != null) {
    const bg = Number(vitals.bloodGlucose);

    if (bg < 3.0) {
      scores.push({
        scoreName: 'Blood Glucose',
        score: bg,
        interpretation: `Severe hypoglycaemia (${bg} mmol/L)`,
        recommendation: 'Immediate IV dextrose (50ml of 50% dextrose) or oral glucose if conscious. Check insulin/OHA doses. Investigate cause.',
        level: 'CRITICAL',
      });
    } else if (bg < 4.0) {
      scores.push({
        scoreName: 'Blood Glucose',
        score: bg,
        interpretation: `Hypoglycaemia (${bg} mmol/L)`,
        recommendation: 'Oral fast-acting carbohydrate. Recheck in 15 minutes. Review diabetic medications.',
        level: 'WARNING',
      });
    } else if (bg > 20) {
      scores.push({
        scoreName: 'Blood Glucose',
        score: bg,
        interpretation: `Severe hyperglycaemia (${bg} mmol/L)`,
        recommendation: 'Check ketones (blood or urine). If DKA: IV insulin infusion, aggressive IV fluids, K+ monitoring. If HHS: IV fluids, cautious insulin.',
        level: 'CRITICAL',
      });
    } else if (bg > 11) {
      scores.push({
        scoreName: 'Blood Glucose',
        score: bg,
        interpretation: `Hyperglycaemia (${bg} mmol/L)`,
        recommendation: 'Review diabetic management. Consider sliding scale insulin if inpatient. Check HbA1c if not recent.',
        level: 'WARNING',
      });
    }
  }

  return scores;
}

/**
 * Checks SOAP note completeness before signing.
 */
export async function reviewSOAPNoteQuality(
  soapNote: {
    subjective: string;
    objective: string;
    assessment: string;
    plan: string;
  },
): Promise<SOAPReviewResult> {
  const fallback: SOAPReviewResult = {
    isComplete: true,
    gaps: [],
    warnings: [],
    suggestions: [],
  };

  try {
    const system = `You are a clinical documentation quality reviewer. Assess SOAP note completeness and quality. Focus on patient safety and medicolegal adequacy.

Respond ONLY with valid JSON, no markdown wrapping:
{
  "isComplete": boolean,
  "gaps": ["missing elements that should be documented"],
  "warnings": ["potential safety/medicolegal concerns"],
  "suggestions": ["improvement suggestions"]
}

Check for:
- Subjective: HPI elements (onset, character, location, duration, severity, aggravating/relieving, associated symptoms), relevant ROS
- Objective: vital signs documented, relevant examination findings, pertinent negatives
- Assessment: clear diagnosis or differential, clinical reasoning
- Plan: specific actionable items, medications with dose/route/frequency, follow-up timeframe, safety-netting advice
- Medicolegal: informed consent documented if procedure, capacity assessment if relevant, chaperone if intimate examination`;

    const prompt = `SOAP Note:

SUBJECTIVE:
${soapNote.subjective || '[EMPTY]'}

OBJECTIVE:
${soapNote.objective || '[EMPTY]'}

ASSESSMENT:
${soapNote.assessment || '[EMPTY]'}

PLAN:
${soapNote.plan || '[EMPTY]'}

Review this note for completeness and quality.`;

    const raw = await callClaude(system, prompt, 800);
    return parseJSON(raw, fallback);
  } catch {
    return fallback;
  }
}

/**
 * Checks drug availability in Nigeria.
 */
export async function checkNigerianFormulary(
  drugName: string,
): Promise<FormularyResult> {
  const fallback: FormularyResult = {
    availabilityStatus: 'UNKNOWN',
    notes: 'Unable to assess formulary status. Verify availability with local pharmacy.',
    alternatives: [],
  };

  try {
    const system = `You are a Nigerian pharmaceutical formulary advisor. Assess drug availability in Nigeria based on your knowledge of NAFDAC-registered medications, Essential Medicines List (Nigeria), and common market availability.

${NIGERIA_CONTEXT}

Respond ONLY with valid JSON, no markdown wrapping:
{
  "availabilityStatus": "AVAILABLE" | "LIMITED" | "UNAVAILABLE" | "UNKNOWN",
  "notes": "availability details, brand names available in Nigeria, typical cost range if known",
  "alternatives": ["NAFDAC-approved alternatives if limited/unavailable"]
}

AVAILABLE: widely available in Nigerian pharmacies
LIMITED: available but may require specialist pharmacy or import
UNAVAILABLE: not registered/marketed in Nigeria
UNKNOWN: insufficient data`;

    const prompt = `Drug: ${drugName}

Assess availability in Nigerian market and suggest alternatives if needed.`;

    const raw = await callClaude(system, prompt, 600);
    return parseJSON(raw, fallback);
  } catch {
    return fallback;
  }
}

/**
 * Generates a formal discharge summary in Nigerian teaching hospital format.
 */
export async function generateDischargeSummary(
  data: {
    patientName: string;
    age: number;
    gender: string;
    hospitalNumber?: string;
    admissionDate: string;
    dischargeDate: string;
    admittingDiagnosis: string;
    finalDiagnosis: string;
    procedures?: string[];
    courseInHospital: string;
    conditionAtDischarge: string;
    medications: Array<{ drugName: string; dose: string; frequency: string; duration?: string }>;
    followUp: string;
    investigations?: string[];
    allergies?: string[];
  },
): Promise<string> {
  const fallback = `DISCHARGE SUMMARY — Unable to generate automatically. Please complete manually.
Patient: ${data.patientName} | Admitted: ${data.admissionDate} | Discharged: ${data.dischargeDate}
Diagnosis: ${data.finalDiagnosis}

${CDSS_DISCLAIMER}`;

  try {
    const system = `You are a clinical documentation assistant generating formal discharge summaries in the standard Nigerian teaching hospital format. Write in professional medical language. Do not invent clinical details — use only what is provided.

${NIGERIA_CONTEXT}

Output a properly formatted discharge summary as plain text (not JSON). Include all standard sections. Append this disclaimer at the end:

"${CDSS_DISCLAIMER}"`;

    const prompt = `Generate a discharge summary:

Patient: ${data.patientName}
Age/Gender: ${data.age} years / ${data.gender}
${data.hospitalNumber ? `Hospital No: ${data.hospitalNumber}` : ''}
Date of Admission: ${data.admissionDate}
Date of Discharge: ${data.dischargeDate}
Admitting Diagnosis: ${data.admittingDiagnosis}
Final Diagnosis: ${data.finalDiagnosis}
${data.procedures?.length ? `Procedures: ${data.procedures.join(', ')}` : ''}
${data.investigations?.length ? `Key Investigations: ${data.investigations.join(', ')}` : ''}
${data.allergies?.length ? `Allergies: ${data.allergies.join(', ')}` : 'Allergies: NKDA'}

Course in Hospital:
${data.courseInHospital}

Condition at Discharge: ${data.conditionAtDischarge}

Discharge Medications:
${data.medications.map((m) => `- ${m.drugName} ${m.dose} ${m.frequency}${m.duration ? ` for ${m.duration}` : ''}`).join('\n')}

Follow-up: ${data.followUp}`;

    return await callClaude(system, prompt, 2000);
  } catch {
    return fallback;
  }
}
