ALTER TABLE "DFCMember" ADD COLUMN IF NOT EXISTS "excoPosition" TEXT;
ALTER TABLE "DFCMember" ADD COLUMN IF NOT EXISTS "excoElectedAt" TIMESTAMP(3);
ALTER TABLE "DFCMember" ADD COLUMN IF NOT EXISTS "excoTermEnd" TIMESTAMP(3);
